-- NextGen Miner: final Premium / hashrate / economy hardening.
-- Already applied to production Supabase; keep this file in GitHub for source/migration parity.
update public.nextgen_membership_plans
set daily_bonus_diamond = case slug when 'premium' then 250 when 'pro' then 750 when 'elite' then 2000 else daily_bonus_diamond end,
 updated_at=now();
update public.nextgen_mining_economy_settings
set monetization_to_mining_bps=2000,max_daily_mining_usd=999999999999999999.000000,updated_at=now() where id=true;
update public.nextgen_mining_pool_settings
set enabled=(upper(asset)='USDT'),pool_share_bps=case when upper(asset)='USDT' then 10000 else 0 end,updated_at=now();
revoke execute on function public.nextgen_request_withdrawal(text,text,numeric,numeric,numeric,text) from anon,authenticated,public;
revoke execute on function public.nextgen_request_withdrawal_v2(text,text,numeric,text) from anon,authenticated,public;
alter table public.nextgen_admins drop constraint if exists nextgen_admins_role_check;
alter table public.nextgen_admins add constraint nextgen_admins_role_check check (role='owner');
update public.nextgen_admins set role='owner' where role<>'owner';
create table if not exists public.nextgen_support_tickets(id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,subject text not null check(char_length(trim(subject)) between 5 and 120),message text not null check(char_length(trim(message)) between 10 and 4000),status text not null default 'open' check(status in ('open','pending','resolved','closed')),priority text not null default 'normal' check(priority in ('low','normal','high')),owner_note text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),resolved_at timestamptz);
alter table public.nextgen_support_tickets enable row level security;
revoke all on public.nextgen_support_tickets from anon,public; grant select,insert on public.nextgen_support_tickets to authenticated;
drop policy if exists support_select_own on public.nextgen_support_tickets; drop policy if exists support_insert_own on public.nextgen_support_tickets;
create policy support_select_own on public.nextgen_support_tickets for select to authenticated using((select auth.uid())=user_id);
create policy support_insert_own on public.nextgen_support_tickets for insert to authenticated with check((select auth.uid())=user_id);
create index if not exists idx_nextgen_support_tickets_user_created on public.nextgen_support_tickets(user_id,created_at desc);
create or replace function public.nextgen_create_support_ticket(p_subject text,p_message text,p_priority text default 'normal') returns jsonb language plpgsql security definer set search_path=public as $$ declare uid uuid:=auth.uid();tid bigint;pr text:=lower(trim(coalesce(p_priority,'normal')));begin if uid is null then raise exception 'AUTH_REQUIRED';end if;if pr not in('low','normal','high')then raise exception 'INVALID_PRIORITY';end if;insert into public.nextgen_support_tickets(user_id,subject,message,priority)values(uid,trim(p_subject),trim(p_message),pr)returning id into tid;return jsonb_build_object('success',true,'ticket_id',tid,'status','open');end;$$;
revoke execute on function public.nextgen_create_support_ticket(text,text,text) from anon,public; grant execute on function public.nextgen_create_support_ticket(text,text,text) to authenticated;
