'use client';
import Link from 'next/link';
import { Boxes, Home, Layers3, LogOut, MoreHorizontal, Package, Target, Trophy, Users, Wallet } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';
const core=[['Home','/dashboard',Home],['Mine','/rooms',Target],['Miners','/miners',Boxes],['Merge','/merge',Layers3],['Quests','/quests',Target],['Wallet','/wallet',Wallet],['History','/wallet/history',Package]] as const;
const account=[['Profile','/profile',Users],['Leaderboard','/leaderboard',Trophy],['More','/more',MoreHorizontal]] as const;
type Props={open:boolean;onClose:()=>void};
export function Sidebar({open,onClose}:Props){const router=useRouter();const[userName,setUserName]=useState('User');const[loggingOut,setLoggingOut]=useState(false);useEffect(()=>{const sb=createClient();let mounted=true;void sb.auth.getUser().then(({data:{user}})=>{if(mounted&&user)setUserName(String(user.user_metadata?.username||user.user_metadata?.full_name||user.email?.split('@')[0]||'User'));});return()=>{mounted=false}},[]);async function logout(){if(loggingOut)return;setLoggingOut(true);await createClient().auth.signOut();onClose();router.replace('/');router.refresh()}const render=(items:ReadonlyArray<readonly [string,string,any]>)=>items.map(([label,href,Icon])=><Link key={label} href={href} className={`nav-item ${label==='Home'?'active':''}`} onClick={onClose}><Icon size={17}/><span>{label}</span></Link>);return <aside className={`sidebar ${open?'open':''} home-sidebar`}><div className="sidebar-head home-sidebar-head"><span>MINING CONTROL</span><button type="button" aria-label="Close menu" onClick={onClose}>×</button></div><nav><div className="sidebar-section-label">CORE</div>{render(core)}<div className="sidebar-section-label" style={{marginTop:15}}>ACCOUNT</div>{render(account)}<button type="button" className="nav-item" onClick={()=>void logout()} disabled={loggingOut}><LogOut size={17}/><span>{loggingOut?'Logging out…':'Logout'}</span></button></nav><div className="sidebar-footer"><Link href="/profile" className="mini-user" onClick={onClose}><div className="avatar">{userName.charAt(0).toUpperCase()}</div><div><b>{userName}</b><small>Standard Member</small></div><span className="dot"/></Link><div className="home-sidebar-version">v2.0.0 · <span>All Systems Operational</span></div></div></aside>}
