'use client';
import Link from 'next/link';
import { ArrowUpCircle, Boxes, Clock3, Crown, Grid2X2, Headphones, Home, Layers3, LogOut, MoreHorizontal, Package, Settings, Target, Trophy, Users, Wallet } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';
const core=[['Home','/dashboard',Home],['Rooms','/rooms',Grid2X2],['Shop / Miners','/miners',Boxes],['Upgrade / Miners','/miners',ArrowUpCircle],['Merge','/merge',Layers3],['Quests','/quests',Target],['Boost Lab','/items',Package],['Wallet','/wallet',Wallet],['History','/wallet/history',Clock3]] as const;
const account=[['Referral','/referrals',Users],['Leaderboard','/leaderboard',Trophy],['Support','/support',Headphones],['Settings','/settings',Settings],['More','/more',MoreHorizontal]] as const;
type Props={open:boolean;onClose:()=>void};
export function Sidebar({open,onClose}:Props){const router=useRouter();const[userName,setUserName]=useState('Account');const[minerLevel,setMinerLevel]=useState<number|null>(null);const[isOwner,setIsOwner]=useState(false);const[loggingOut,setLoggingOut]=useState(false);useEffect(()=>{const sb=createClient();let mounted=true;void(async()=>{const{data:{user}}=await sb.auth.getUser();if(!user||!mounted)return;const name=user.user_metadata?.username||user.user_metadata?.full_name||user.email?.split('@')[0];if(name)setUserName(String(name));const ownerResult=await sb.rpc('nextgen_is_owner');if(mounted&&!ownerResult.error&&ownerResult.data===true)setIsOwner(true);const{data}=await sb.from('nextgen_user_miners').select('current_level').eq('user_id',user.id).order('current_level',{ascending:false}).limit(1).maybeSingle();if(mounted)setMinerLevel(data?.current_level==null?null:Number(data.current_level))})();return()=>{mounted=false}},[]);async function logout(){if(loggingOut)return;setLoggingOut(true);await createClient().auth.signOut();onClose();router.replace('/');router.refresh()}const render=(items:ReadonlyArray<readonly [string,string,any]>)=>items.map(([label,href,Icon])=><Link key={label} href={href} className="nav-item" onClick={onClose}><Icon size={17}/><span>{label}</span></Link>);return <aside className={`sidebar ${open?'open':''}`}><div className="sidebar-head"><span>MINING CONTROL GRID</span><button type="button" aria-label="Close menu" onClick={onClose}>×</button></div>{isOwner?<div className="sidebar-owner-section"><div className="sidebar-section-label">OWNER</div><Link href="/owner" className="nav-item nav-item--owner" onClick={onClose}><Crown size={17}/><span>Owner Control</span></Link></div>:null}<nav><div className="sidebar-section-label">CORE MINING</div>{render(core)}<div className="sidebar-section-label" style={{marginTop:12}}>ACCOUNT</div>{render(account)}<button type="button" className="nav-item" onClick={()=>void logout()} disabled={loggingOut} style={{width:'100%',background:'transparent',cursor:loggingOut?'wait':'pointer'}}><LogOut size={17}/><span>{loggingOut?'Logging out…':'Logout'}</span></button></nav><div className="sidebar-footer"><Link href="/profile" className="mini-user" onClick={onClose}><div className="avatar">{userName.charAt(0).toUpperCase()}</div><div><b>{userName}</b><small>{isOwner?'OWNER':minerLevel===null?'No miner yet':`Level ${minerLevel}`}</small></div><span className="dot"/></Link></div></aside>}
