import { AppShell } from '@/components/layout/AppShell';
import { EconomicDashboardRefresh } from '@/components/admin/EconomicDashboardRefresh';
import { createClient } from '@/lib/supabase/server';
import { revalidatePath } from 'next/cache';

export const dynamic='force-dynamic'; export const revalidate=0;
const n=(v:any,d=2)=>{const x=Number(v??0);return Number.isFinite(x)?x.toLocaleString('en-US',{maximumFractionDigits:d}):'0'};
const money=(v:any,d=2)=>`$${n(v,d)}`;
const arr=(v:any)=>Array.isArray(v)?v:[];
const badge=(s:string)=>['HEALTHY','PASS','INFO','RESOLVED'].includes(s)?'badge green':['PRESSURE','WARN','ACKNOWLEDGED'].includes(s)?'badge gold':'badge';
async function ackA(f:FormData){'use server';const id=Number(f.get('id'));if(!Number.isInteger(id))return;const s=await createClient();await s.rpc('nextgen_ack_economic_anomaly',{p_anomaly_id:id,p_note:'Acknowledged from owner dashboard.'});revalidatePath('/admin/economic-monitoring')}
async function resA(f:FormData){'use server';const id=Number(f.get('id'));const note=String(f.get('note')??'').trim();if(!Number.isInteger(id)||!note)return;const s=await createClient();await s.rpc('nextgen_resolve_economic_anomaly',{p_anomaly_id:id,p_resolution_note:note});revalidatePath('/admin/economic-monitoring')}
async function ackL(f:FormData){'use server';const id=Number(f.get('id'));if(!Number.isInteger(id))return;const s=await createClient();await s.rpc('nextgen_ack_economic_alert',{p_alert_id:id});revalidatePath('/admin/economic-monitoring')}
async function resL(f:FormData){'use server';const id=Number(f.get('id'));const note=String(f.get('note')??'').trim();if(!Number.isInteger(id)||!note)return;const s=await createClient();await s.rpc('nextgen_resolve_economic_alert',{p_alert_id:id,p_resolution_note:note});revalidatePath('/admin/economic-monitoring')}

export default async function EconomicMonitoringPage(){
 const s=await createClient();
 const {data,error}=await s.rpc('nextgen_economic_monitoring_v2_snapshot',{p_asset:'USDT'});
 const x=(data??{}) as Record<string,any>, g=x.guard??{}, a=x.provider_settlement_aging??x.revenue_aging??{}, r=x.reversal_recovery??{}, rt=x.reserve_trend??{}, lc=x.anomaly_lifecycle??{}, ge=x.guard_escalation??{};
 const anomalies=arr(x.open_anomalies),alerts=arr(x.open_alerts),trans=arr(x.guard_transitions),runs=arr(x.recent_monitoring_runs);
 const settlements=arr(a.rows??a.settlements??x.provider_settlements),trend=arr(rt.rows??rt.history??x.reserve_snapshots);
 const status=String(g.status??'UNAVAILABLE');
 return <AppShell><EconomicDashboardRefresh intervalMs={60000}/><div className="page-head"><div><div className="eyebrow">OWNER CONTROL · ECONOMIC MONITORING V2</div><h1 className="page-title">Economic Monitoring & Reconciliation</h1><div className="muted">Settlement aging, reversal/recovery, reserve trend, anomaly lifecycle, and capacity-guard escalation.</div></div><div className={badge(status)}>{status}</div></div>
 {error?<section className="glass section"><div className="eyebrow">CONTROL PLANE</div><h2>Monitoring unavailable</h2><p className="muted">The owner-only CP15 monitoring snapshot could not be loaded.</p></section>:<>
 <div className="grid grid-4">
 <div className="glass stat"><label>Open anomalies</label><b>{n(lc.open??anomalies.length,0)}</b></div><div className="glass stat"><label>Acknowledged</label><b>{n(lc.acknowledged,0)}</b></div><div className="glass stat"><label>Resolved ≤24h</label><b>{n(lc.resolved_24h,0)}</b></div><div className="glass stat"><label>Guard escalation</label><b>{String(ge.escalation_level??'NONE')}</b></div></div>
 <div className="grid grid-4" style={{marginTop:14}}><div className="glass stat"><label>Pending ≤24h</label><b>{money(a.pending_0_24h_usd)}</b></div><div className="glass stat"><label>Pending 24–72h</label><b>{money(a.pending_24_72h_usd)}</b></div><div className="glass stat"><label>Stale &gt;72h</label><b>{money(a.stale_72h_plus_usd)}</b></div><div className="glass stat"><label>Reversed</label><b>{money(r.reversed_usd,4)}</b></div></div>
 <div className="grid grid-2" style={{marginTop:14}}>
 <section className="glass section"><div className="eyebrow">SETTLEMENT AGING</div><h2>Provider recovery queue</h2><div className="list-row"><span>0–24h</span><b>{n(a.pending_0_24h_count,0)}</b></div><div className="list-row"><span>24–72h</span><b>{n(a.pending_24_72h_count,0)}</b></div><div className="list-row"><span>72h+</span><b>{n(a.pending_72h_plus_count??a.stale_72h_plus_count,0)}</b></div><div className="list-row"><span>Recoverable net</span><b>{money(a.recoverable_net_revenue_usd,4)}</b></div>{settlements.slice(0,8).map((q:any)=><div className="list-row" key={String(q.id??q.external_reference)}><span>{String(q.provider_key??q.external_reference??'Settlement')} · {String(q.status??'UNKNOWN')}</span><b>{money(q.net_revenue_usd??q.recoverable_net_revenue_usd,4)}</b></div>)}{!settlements.length&&<p className="muted">No provider settlement records are currently present.</p>}</section>
 <section className="glass section"><div className="eyebrow">REVERSAL / RECOVERY</div><h2>Revenue recovery control</h2><div className="list-row"><span>Settled gross</span><b>{money(r.gross_revenue_usd,4)}</b></div><div className="list-row"><span>User reward</span><b>{money(r.user_reward_usd,4)}</b></div><div className="list-row"><span>Net revenue</span><b>{money(r.net_revenue_usd,4)}</b></div><div className="list-row"><span>Reversed USD</span><b>{money(r.reversed_usd,4)}</b></div><div className="list-row"><span>Recoverable USD</span><b>{money(r.recoverable_usd,4)}</b></div><div className="list-row"><span>Recovery events</span><b>{n(r.recovery_event_count,0)}</b></div></section></div>
 <div className="grid grid-2" style={{marginTop:14}}>
 <section className="glass section"><div className="eyebrow">RESERVE TREND</div><h2>Safety buffer history</h2><div className="list-row"><span>Current reserve</span><b>{money(rt.current_reserve_balance_usd,8)}</b></div><div className="list-row"><span>Current liability</span><b>{money(rt.current_open_liability_usd,8)}</b></div><div className="list-row"><span>Coverage ratio</span><b>{n(rt.current_reserve_coverage_ratio,3)}×</b></div><div className="list-row"><span>Mining budget</span><b>{money(rt.current_mining_budget_usd,8)}</b></div>{trend.slice(-8).map((q:any,i:number)=><div className="list-row" key={String(q.id??q.snapshot_at??i)}><span>{String(q.snapshot_at??q.at??'snapshot')}</span><b>{money(q.reserve_balance_usd,6)}</b></div>)}</section>
 <section className="glass section"><div className="eyebrow">GUARD ESCALATION</div><h2>Capacity safety state</h2><div className="list-row"><span>Current status</span><b className={badge(status)}>{status}</b></div><div className="list-row"><span>Expansion allowed</span><b>{g.expansion_allowed?'YES':'NO'}</b></div><div className="list-row"><span>Utilization</span><b>{n(g.capacity_utilization_percent,2)}%</b></div><div className="list-row"><span>Mining budget</span><b>{money(g.mining_budget_usd,8)}</b></div><div className="list-row"><span>Escalation level</span><b>{String(ge.escalation_level??'NONE')}</b></div><div className="list-row"><span>Reason</span><b>{String(ge.reason??g.reason??'—')}</b></div></section></div>
 <div className="grid grid-2" style={{marginTop:14}}>
 <section className="glass section"><div className="eyebrow">ANOMALY LIFECYCLE</div><h2>ACK / resolution queue</h2>{!anomalies.length?<p className="muted">No open economic anomalies.</p>:anomalies.slice(0,12).map((q:any)=><div key={String(q.id??q.fingerprint)} style={{padding:'12px 0',borderBottom:'1px solid rgba(255,255,255,.07)'}}><div className="list-row"><span>{String(q.title??q.anomaly_code)}</span><b className={badge(String(q.status??q.severity??'OPEN'))}>{String(q.status??'OPEN')}</b></div><div className="muted" style={{marginTop:6}}>{String(q.details??'')}</div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:9}}>{String(q.status??'OPEN')==='OPEN'&&<form action={ackA}><input type="hidden" name="id" value={String(q.id)}/><button className="public-button" type="submit">Acknowledge</button></form>}{String(q.status??'OPEN')!=='RESOLVED'&&<form action={resA} style={{display:'flex',gap:7,flexWrap:'wrap'}}><input name="note" required minLength={3} placeholder="Resolution note"/><input type="hidden" name="id" value={String(q.id)}/><button className="public-button-primary" type="submit">Resolve</button></form>}</div></div>)}</section>
 <section className="glass section"><div className="eyebrow">ALERT LIFECYCLE</div><h2>Operator ACK / resolution</h2>{!alerts.length?<p className="muted">Alert queue is clear.</p>:alerts.slice(0,12).map((q:any)=><div key={String(q.id??q.alert_key)} style={{padding:'12px 0',borderBottom:'1px solid rgba(255,255,255,.07)'}}><div className="list-row"><span>{String(q.title??q.alert_key)}</span><b className={badge(String(q.status??q.severity??'OPEN'))}>{String(q.status??'OPEN')}</b></div><div className="muted" style={{marginTop:6}}>{String(q.body??'')}</div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:9}}>{String(q.status??'OPEN')==='OPEN'&&<form action={ackL}><input type="hidden" name="id" value={String(q.id)}/><button className="public-button" type="submit">Acknowledge</button></form>}{String(q.status??'OPEN')!=='RESOLVED'&&<form action={resL} style={{display:'flex',gap:7,flexWrap:'wrap'}}><input name="note" required minLength={3} placeholder="Resolution note"/><input type="hidden" name="id" value={String(q.id)}/><button className="public-button-primary" type="submit">Resolve</button></form>}</div></div>)}</section></div>
 <div className="grid grid-2" style={{marginTop:14}}><section className="glass section"><div className="eyebrow">GUARD HISTORY</div><h2>Capacity state changes</h2>{trans.slice(0,12).map((q:any)=><div className="list-row" key={String(q.id)}><span>{String(q.from_status??'START')} → {String(q.to_status)}</span><b>{String(q.transition_type)}</b></div>)}</section><section className="glass section"><div className="eyebrow">WORKER HISTORY</div><h2>Recent CP15 runs</h2>{runs.slice(0,12).map((q:any)=><div className="list-row" key={String(q.id)}><span>{String(q.run_at)} · anomalies {n(q.anomaly_count,0)} · alerts {n(q.alert_count,0)}</span><b className={badge(String(q.severity??'INFO'))}>{String(q.severity??'INFO')}</b></div>)}</section></div>
 </>}</AppShell>
}
