'use client';

import Link from 'next/link';
import { Activity, ArrowRight, Boxes, CircleDollarSign, Gauge, History, Layers3, RefreshCw, ShieldCheck, Sparkles, Target, Wallet, Zap } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import styles from './HomeCommandCenter.module.css';

export type HomeSnapshot = {
  engine:string; today_utc:string; asset:string; diamond_balance:number|string; reserved_diamond:number|string;
  active_miners:number; active_hashrate:number|string; effective_hashrate:number|string;
  room:{name:string;room_count:number;capacity:number;workers:number;load_percent:number|string;hashrate:number|string};
  hashrate_status:{status:string;recharge_expires_at:string|null;premium:boolean;membership_expires_at:string|null};
  membership:{active:boolean;slug:string;name:string;mining_factor:number|string;task_multiplier:number|string;referral_multiplier:number|string;task_limit_multiplier:number|string;upgrade_discount_bps:number;daily_bonus_diamond:number|string;premium_miner_access:boolean;priority_support:boolean;early_access:boolean;expires_at:string|null};
  pool:{pool_date:string;asset:string;mining_budget_usd:number|string;allocated_usd:number|string;reward_rate_usd_per_hash_second:number|string;reserve_balance_usd:number|string;reserve_coverage_ratio:number|string;reserve_status:string;network_baseline_hashrate:number|string;network_baseline_weight:number|string;prepared_at:string|null;mining_allocation_bps:number;reserve_allocation_bps:number;rolling_10d_net_revenue_usd:number|string;rolling_10d_mining_release_usd:number|string;mining_lot_days:number}|null;
  selected_asset:{asset:string;display_name:string;mining_enabled:boolean;pool_enabled:boolean;rate_usd:number|string;rate_updated_at:string|null;status:string};
  live_earnings:{status:string;estimated_usd:number|string;estimated_crypto:number|string;elapsed_seconds:number|string;currency:string;claim_is_server_settled:boolean};
  streak:{current:number;best:number;today_claimed:boolean;base_reward_diamond:number|string;days:Array<{day:number;status:'claimed'|'ready'|'locked';reward_diamond:number|string}>};
  bonuses:Array<{key:string;label:string;value:string;active:boolean}>;
  crypto_options:Array<{asset:string;display_name:string;mining_enabled:boolean;pool_enabled:boolean;rate_usd:number|string;rate_updated_at:string|null;status:string}>;
  earnings_history:Array<{date:string;allocated_usd:number|string;crypto_amount:number|string}>;
  recent_transactions:Array<{id:number;type:string;diamond_delta:number|string;usd_delta:number|string;asset:string|null;crypto_amount:number|string|null;created_at:string}>;
};

type ClaimStatus={asset:string;settlement_date:string;status:'READY'|'ALREADY_SETTLED'|'NOT_READY';reason:string;payout_id:number|null;mining_budget_usd:number|string;pool_prepared:boolean};
const n=(v:number|string|null|undefined,d=2)=>Number(v??0).toLocaleString('en-US',{maximumFractionDigits:d});
const money=(v:number|string|null|undefined)=>Number(v??0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:8});
const crypto=(v:number|string|null|undefined)=>Number(v??0).toLocaleString('en-US',{maximumFractionDigits:8});
const pct=(v:number|string|null|undefined)=>`${Number(v??0).toFixed(1)}%`;
function err(e:unknown){if(e&&typeof e==='object'&&'message' in e)return String((e as any).message??'Action failed');return e instanceof Error?e.message:'Action failed';}
function path(values:number[]){const width=600,height=180,pad=18,max=Math.max(...values,0.0000001),min=Math.min(...values,0),span=Math.max(max-min,0.0000001);return values.map((v,i)=>{const x=pad+(i/Math.max(values.length-1,1))*(width-pad*2);const y=height-pad-((v-min)/span)*(height-pad*2);return `${i?'L':'M'}${x.toFixed(2)},${y.toFixed(2)}`}).join(' ')}

export function HomeCommandCenter({initialData}:{initialData:HomeSnapshot}){
 const [data,setData]=useState(initialData); const [claim,setClaim]=useState<ClaimStatus|null>(null); const [asset,setAsset]=useState(initialData.asset); const [loading,setLoading]=useState(false); const [claiming,setClaiming]=useState(false); const [checkingIn,setCheckingIn]=useState(false); const [message,setMessage]=useState('');
 const load=useCallback(async(nextAsset=asset,silent=false)=>{const sb=createClient();if(!silent)setLoading(true);try{const[a,c]=await Promise.all([sb.rpc('nextgen_farm_snapshot',{p_asset:nextAsset}),sb.rpc('nextgen_farm_claim_status',{p_asset:nextAsset})]);if(a.error)throw a.error;if(c.error)throw c.error;setData(a.data as HomeSnapshot);setClaim(c.data as ClaimStatus);setAsset(nextAsset);}catch(e){setMessage(err(e));}finally{if(!silent)setLoading(false)}},[asset]);
 useEffect(()=>{void load(asset,true);const t=window.setInterval(()=>void load(asset,true),15000);return()=>window.clearInterval(t)},[asset,load]);
 const values=useMemo(()=>data.earnings_history.map(x=>Number(x.allocated_usd??0)),[data.earnings_history]); const chart=useMemo(()=>path(values.length?values:[0,0]),[values]); const positive=values.some(v=>v>0); const activeBonuses=data.bonuses.filter(x=>x.active).length; const live=Number(data.live_earnings.estimated_crypto??0);
 async function settle(){if(claim?.status!=='READY'||claiming)return;setClaiming(true);setMessage('');try{const sb=createClient();const r=await sb.rpc('nextgen_claim_mining',{p_asset:asset});if(r.error)throw r.error;setMessage(r.data?.settled?`Settlement ${r.data?.payout_id?`#${r.data.payout_id}`:''} posted successfully.`:String(r.data?.reason??'No settlement was available.'));await load(asset,true)}catch(e){setMessage(err(e))}finally{setClaiming(false)}}
 async function checkIn(){if(checkingIn||data.streak.today_claimed)return;setCheckingIn(true);setMessage('');try{const sb=createClient();const r=await sb.rpc('nextgen_claim_daily_checkin');if(r.error)throw r.error;setMessage(`Daily check-in claimed: ${n(r.data?.diamond_awarded,0)} 💎.`);await load(asset,true)}catch(e){setMessage(err(e))}finally{setCheckingIn(false)}}
 return <div className={styles.shell}>
  <section className={styles.hero}><div className={styles.heroGrid}><div><div className={styles.liveHeader}><div><div className={styles.kicker}>HOME / LIVE EARNINGS</div><h1 className={styles.title}>Your Mining Core</h1><div className={styles.muted}>Server-calculated mining state, pool status and user earnings. No synthetic balance growth is rendered.</div></div><span className={`${styles.status} ${data.live_earnings.status==='WAITING_FOR_FUNDED_POOL'?styles.off:''}`}><Activity size={13}/>{data.live_earnings.status==='WAITING_FOR_FUNDED_POOL'?'WAITING':'ONLINE'}</span></div>
   <div className={styles.liveValue}>{crypto(live)}<span className={styles.liveUnit}>{asset}</span></div><div className={styles.muted}>Estimated live accrual from the current funded pool. Current budget: ${money(data.pool?.mining_budget_usd)}.</div>
   <div className={styles.pending}><div><small>PENDING / ESTIMATED</small><strong>{money(data.live_earnings.estimated_usd)} USD · {crypto(data.live_earnings.estimated_crypto)} {asset}</strong></div><Gauge size={24}/></div>
   <div className={styles.heroActions}><button className={styles.primary} disabled={claim?.status!=='READY'||claiming} onClick={()=>void settle()}><Zap size={16}/>{claiming?'SYNCING…':claim?.status==='READY'?'CLAIM LAST SETTLEMENT':'NO CLAIM AVAILABLE'}</button><button className={styles.ghost} disabled={loading} onClick={()=>void load(asset)}><RefreshCw size={15}/>{loading?'Refreshing…':'Refresh Core'}</button><Link href="/miners" className={styles.ghost}><Boxes size={15}/>Miner Arsenal</Link></div>
  </div><div className={styles.sideGrid}><div className={styles.stat}><span>ACTIVE HASHRATE</span><strong>{n(data.active_hashrate)} H/s</strong></div><div className={styles.stat}><span>EFFECTIVE HASHRATE</span><strong>{n(data.effective_hashrate)} H/s</strong></div><div className={styles.stat}><span>ACTIVE MINERS</span><strong>{data.active_miners}</strong></div><div className={styles.stat}><span>DIAMOND BALANCE</span><strong>{n(data.diamond_balance,0)} 💎</strong></div><div className={styles.stat}><span>NETWORK BASELINE</span><strong>{n(data.pool?.network_baseline_hashrate)} H/s</strong></div><div className={styles.stat}><span>POOL STATUS</span><strong>{data.pool?.reserve_status??'NOT PREPARED'}</strong></div></div></div></section>
  {message?<section className={styles.section}><div className={styles.link}><ShieldCheck size={18}/>{message}</div></section>:null}
  <section className={styles.grid2}><div className={styles.section}><div className={styles.sectionHead}><div><div className={styles.kicker}>COMPUTE BAYS</div><h2>Starter Compute Bay</h2></div><Link href="/rooms" className={styles.link}>Open Rooms <ArrowRight size={13}/></Link></div><div className={styles.roomVisual}><div className={styles.roomTunnel}>{Array.from({length:data.room.capacity}).map((_,i)=><div key={i} className={`${styles.slot} ${i>=data.room.workers?styles.empty:''}`}>{i<data.room.workers?'W':'·'}</div>)}</div><div className={styles.roomMeta}><div><span>COMPUTE BAYS</span><b>{data.room.room_count}</b></div><div><span>WORKERS</span><b>{data.room.workers}/{data.room.capacity}</b></div><div><span>LOAD</span><b>{pct(data.room.load_percent)}</b></div><div><span>HASHRATE</span><b>{n(data.room.hashrate)} H/s</b></div></div></div></div>
   <div className={styles.section}><div className={styles.sectionHead}><div><div className={styles.kicker}>CORE STATE</div><h2>Core Health</h2></div><Sparkles size={18}/></div><div className={styles.miniGrid}><div className={styles.miniCard}><small>HASHRATE STATUS</small><b>{data.hashrate_status.status.replaceAll('_',' ')}</b></div><div className={styles.miniCard}><small>RECHARGE</small><b>{data.hashrate_status.premium?'PREMIUM':data.hashrate_status.recharge_expires_at?new Date(data.hashrate_status.recharge_expires_at).toLocaleString('id-ID'):'NOT ACTIVE'}</b></div><div className={styles.miniCard}><small>RULE ENGINE</small><b>{data.engine}</b></div><div className={styles.miniCard}><small>POOL RAIL</small><b>{asset} · {data.selected_asset.status}</b></div></div><div className={styles.muted} style={{marginTop:12}}>Membership factor {Number(data.membership.mining_factor).toFixed(2)}x · effective H/s includes server energy/efficiency state.</div></div></section>
  <section className={styles.section}><div className={styles.sectionHead}><div><div className={styles.kicker}>CRYPTO MATRIX</div><h2>Choose an Output Rail</h2></div><CircleDollarSign size={19}/></div><div className={styles.muted}>Wallet assets and mining rails are distinct. An asset is shown as ACTIVE only when its pool rail is enabled and its exchange rate is fresh.</div><div className={styles.cryptoGrid}>{data.crypto_options.map(o=>{const active=o.asset===asset;const liveRail=o.status==='ACTIVE';return <button key={o.asset} type="button" className={`${styles.crypto} ${active?styles.active:''} ${liveRail?'':styles.offline}`} onClick={()=>void load(o.asset)}><b>{o.asset}</b><span>{o.display_name}</span><span>{o.rate_usd?`$${n(o.rate_usd,8)}`:'rate unavailable'}</span><span className={`${styles.cryptoTag} ${liveRail?styles.activeTag:styles.offTag}`}>{o.status.replaceAll('_',' ')}</span></button>})}</div><div className={styles.muted} style={{marginTop:10}}>Selected: <strong>{data.selected_asset.display_name}</strong> · rate ${n(data.selected_asset.rate_usd,8)} · live estimate {crypto(live)} {asset}.</div></section>
  <section className={styles.grid2}><div className={styles.section}><div className={styles.sectionHead}><div><div className={styles.kicker}>DAILY STREAK</div><h2>Daily Pulse</h2></div><Target size={18}/></div><div className={styles.twoColList}><div className={styles.listItem}><span>Current streak</span><strong>{data.streak.current} days</strong></div><div className={styles.listItem}><span>Best streak</span><strong>{data.streak.best} days</strong></div><div className={styles.listItem}><span>Base check-in</span><strong>{n(data.streak.base_reward_diamond,0)} 💎</strong></div><div className={styles.listItem}><span>Today</span><strong>{data.streak.today_claimed?'CLAIMED':'READY'}</strong></div></div><div className={styles.streakGrid}>{data.streak.days.map(d=><div key={d.day} className={`${styles.streak} ${d.status==='claimed'?styles.claimed:d.status==='ready'?styles.ready:styles.locked}`}><b>D{d.day}</b><span>{d.status.toUpperCase()}</span></div>)}</div><button className={styles.primary} style={{marginTop:12,width:'100%'}} disabled={data.streak.today_claimed||checkingIn} onClick={()=>void checkIn()}>{checkingIn?'CHECKING IN…':data.streak.today_claimed?'CLAIMED · RETURN TOMORROW':'CLAIM DAILY CHECK-IN'}</button></div>
    <div className={styles.section}><div className={styles.sectionHead}><div><div className={styles.kicker}>PERFORMANCE MATRIX</div><h2>Active Modifiers</h2></div><Sparkles size={18}/></div><div className={styles.muted}>Only entitlements that exist in the current membership model are shown as active.</div><div className={styles.bonusGrid}>{data.bonuses.map(b=><div key={b.key} className={`${styles.bonus} ${b.active?styles.active:''}`}><span>{b.label}</span><b>{b.value}</b></div>)}</div><div className={styles.muted} style={{marginTop:10}}>{activeBonuses} active benefit{activeBonuses===1?'':'s'} · membership: {data.membership.name}.</div></div></section>
  <section className={styles.section}><div className={styles.sectionHead}><div><div className={styles.kicker}>EARNINGS SIGNAL</div><h2>Earnings Signal</h2></div><History size={18}/></div><div className={styles.chartWrap}><svg className={styles.chart} viewBox="0 0 600 180" role="img" aria-label="Mining earnings history"><line className={styles.chartZero} x1="18" x2="582" y1="162" y2="162" />{positive?<path className={styles.chartArea} d={`${chart} L582,162 L18,162 Z`}/>:null}<path className={styles.chartLine} d={chart}/></svg><div className={styles.chartLabels}>{data.earnings_history.map(r=><span key={r.date}>{r.date.slice(5)}</span>)}</div></div><div className={styles.muted} style={{marginTop:10}}>{positive?'Historical values are settled user mining payouts from the database.':'No settled mining payout exists yet. The chart remains at zero instead of fabricating earnings.'}</div></section>
  <section className={styles.activityGrid}><Link href="/miners" className={styles.activity}><Boxes size={18}/><b>Miners</b><span>Buy, upgrade and compare all 12 miner families.</span></Link><Link href="/merge" className={styles.activity}><Layers3 size={18}/><b>Merge</b><span>Combine identical miners using database-controlled merge fees.</span></Link><Link href="/quests" className={styles.activity}><Target size={18}/><b>Quests</b><span>Track supported Diamond engagement objectives.</span></Link><Link href="/wallet/history" className={styles.activity}><History size={18}/><b>History</b><span>Review transaction and mining ledger history.</span></Link></section>
  <section className={styles.grid3}><div className={styles.section}><div className={styles.kicker}>DIAMOND</div><div className={styles.liveValue} style={{fontSize:30}}>{n(data.diamond_balance,0)} <span className={styles.liveUnit}>💎</span></div><div className={styles.muted}>Internal utility balance for miners, upgrades and merge fees.</div></div><div className={styles.section}><div className={styles.kicker}>MINING POOL</div><div className={styles.liveValue} style={{fontSize:30}}>${money(data.pool?.mining_budget_usd)}</div><div className={styles.muted}>{data.pool?.mining_allocation_bps??0} bps mining · {data.pool?.reserve_allocation_bps??0} bps reserve.</div></div><div className={styles.section}><div className={styles.kicker}>WALLET / HISTORY</div><div className={styles.heroActions}><Link href="/wallet" className={styles.ghost}><Wallet size={15}/>Wallet</Link><Link href="/wallet/history" className={styles.ghost}><History size={15}/>History</Link></div></div></section>
  <section className={styles.section}><div className={styles.sectionHead}><div><div className={styles.kicker}>RECENT ACTIVITY</div><h2>Account Ledger</h2></div><History size={18}/></div>{data.recent_transactions.length===0?<div className={styles.muted}>No account transaction recorded yet.</div>:<div className={styles.twoColList}>{data.recent_transactions.map(tx=><div key={tx.id} className={styles.listItem}><span>{tx.type.replaceAll('_',' ')}</span><strong>{tx.diamond_delta?`${n(tx.diamond_delta,2)} 💎`:tx.crypto_amount?`${crypto(tx.crypto_amount)} ${tx.asset??''}`:`${money(tx.usd_delta)} USD`}</strong></div>)}</div>}</section>
  <section className={styles.section}><div className={styles.sectionHead}><div><div className={styles.kicker}>CORE PRINCIPLE</div><h2>Revenue-funded. Server-settled. No guaranteed yield.</h2></div><ShieldCheck size={19}/></div><div className={styles.muted}>Mining rewards are created only from a funded pool. Free rewards and internal Diamond do not create crypto liabilities by themselves.</div></section>
 </div>
}
