'use client'
import {FormEvent,useEffect,useState} from 'react'
import {AppShell} from '@/components/layout/AppShell'
import styles from './support.module.css'
type Ticket={id:number;subject:string;message:string;status:string;priority:string;owner_note?:string|null;created_at:string;updated_at:string;resolved_at?:string|null}
export default function SupportPage(){const[tickets,setTickets]=useState<Ticket[]>([]),[subject,setSubject]=useState(''),[message,setMessage]=useState(''),[priority,setPriority]=useState('normal'),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
 const load=async()=>{const r=await fetch('/api/support');const d=await r.json().catch(()=>({}));if(r.ok)setTickets(d.tickets??[])};useEffect(()=>{void load()},[])
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setNotice('');const r=await fetch('/api/support',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({subject,message,priority})});const d=await r.json().catch(()=>({}));if(!r.ok)setNotice(String(d.error??'Tidak dapat mengirim ticket.'));else{setNotice(`Ticket #${d.ticket_id} berhasil dibuat.`);setSubject('');setMessage('');await load()}setBusy(false)}
 return <AppShell><div className={styles.page}><div className={styles.head}><div className="eyebrow">SUPPORT CENTER</div><h1 className="page-title">Support</h1><p className="muted">Hubungi support tanpa memberikan akses finansial atau data sensitif.</p></div><div className={styles.grid}><form className={`glass ${styles.card}`} onSubmit={submit}><h2>Open Ticket</h2><label>SUBJECT<input className="input" value={subject} onChange={e=>setSubject(e.target.value)} minLength={5} maxLength={120} required/></label><label>PRIORITY<select className="input" value={priority} onChange={e=>setPriority(e.target.value)}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option></select></label><label>MESSAGE<textarea className="input" value={message} onChange={e=>setMessage(e.target.value)} minLength={10} maxLength={4000} rows={7} required/></label>{notice&&<p className="muted">{notice}</p>}<button className="btn btn-primary" disabled={busy}>{busy?'Sending…':'Send Ticket'}</button></form><section className={`glass ${styles.card}`}><h2>My Tickets</h2>{tickets.length?tickets.map(t=><article className={styles.ticket} key={t.id}><div><b>#{t.id} · {t.subject}</b><span>{t.status.toUpperCase()} · {t.priority}</span></div><p>{t.message}</p>{t.owner_note?<small>Owner: {t.owner_note}</small>:null}<time>{new Date(t.created_at).toLocaleString('id-ID')}</time></article>):<p className="muted">Belum ada ticket.</p>}</section></div></div></AppShell>}
