create table if not exists public.nextgen_wallets (
  user_id uuid primary key references auth.users(id) on delete cascade,
  diamond_balance numeric(30,8) not null default 0 check (diamond_balance >= 0),
  reserved_diamond numeric(30,8) not null default 0 check (reserved_diamond >= 0),
  usd_value numeric(30,8) not null default 0 check (usd_value >= 0),
  qualifying_topup_usd numeric(30,8) not null default 0 check (qualifying_topup_usd >= 0),
  updated_at timestamptz not null default now()
);
create table if not exists public.nextgen_miner_catalog (
 id bigint generated by default as identity primary key,
 slug text unique not null,
 name text not null,
 tier text not null,
 base_hashrate numeric not null check(base_hashrate>0),
 base_price_diamond numeric not null default 0 check(base_price_diamond>=0),
 image_path text not null,
 sort_order int not null default 0,
 enabled boolean not null default true
);
create table if not exists public.nextgen_miner_levels (
 id bigint generated by default as identity primary key,
 miner_id bigint not null references public.nextgen_miner_catalog(id) on delete cascade,
 level int not null check(level between 1 and 10),
 hashrate numeric not null check(hashrate>0),
 upgrade_price_diamond numeric not null default 0 check(upgrade_price_diamond>=0),
 cumulative_price_diamond numeric not null default 0 check(cumulative_price_diamond>=0),
 unique(miner_id,level)
);
create table if not exists public.nextgen_user_miners (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 miner_id bigint not null references public.nextgen_miner_catalog(id),
 current_level int not null default 1 check(current_level between 1 and 10),
 total_spent_diamond numeric(30,8) not null default 0 check(total_spent_diamond>=0),
 status text not null default 'active' check(status in ('active','paused')),
 activated_at timestamptz not null default now(),
 last_upgrade_at timestamptz,
 unique(user_id,miner_id)
);
create table if not exists public.nextgen_transactions (
 id bigint generated by default as identity primary key,
 user_id uuid references auth.users(id),
 tx_type text not null,
 diamond_delta numeric(30,8) not null default 0,
 usd_delta numeric(30,8) not null default 0,
 asset text, network text, crypto_amount numeric(30,18), reference_id text, note text,
 created_at timestamptz not null default now()
);
create table if not exists public.nextgen_deposits (
 id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,
 asset text not null,network text not null,amount numeric(30,18) not null,usd_amount numeric(30,8) not null,
 diamond_amount numeric(30,8) not null,tx_hash text,status text not null default 'pending' check(status in('pending','approved','rejected')),
 created_at timestamptz not null default now(), reviewed_at timestamptz
);
create table if not exists public.nextgen_withdrawals (
 id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,
 asset text not null,network text not null,diamond_amount numeric(30,8) not null,usd_amount numeric(30,8) not null,
 crypto_amount numeric(30,18),destination text not null,status text not null default 'pending' check(status in('pending','approved','rejected')),
 created_at timestamptz not null default now(), reviewed_at timestamptz
);
create table if not exists public.nextgen_reward_ledger (
 id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,
 source_key text not null,amount_diamond numeric(30,8) not null,external_reference text unique,
 status text not null default 'posted' check(status in('pending','posted','reversed','rejected')),metadata jsonb not null default '{}',created_at timestamptz not null default now()
);
create table if not exists public.nextgen_faucet_claims (
 id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,
 reward_diamond numeric(30,8) not null,claimed_at timestamptz not null default now(),external_reference text unique,metadata jsonb not null default '{}'
);
create table if not exists public.nextgen_ptc_campaigns (
 id bigint generated by default as identity primary key,title text not null,duration_seconds int not null default 15,
 target_url text not null,revenue_usd numeric(30,8) not null default 0,reward_share_bps int not null default 2000,
 enabled boolean not null default true
);
create table if not exists public.nextgen_ptc_sessions (
 id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,
 campaign_id bigint not null references public.nextgen_ptc_campaigns(id),external_reference text unique not null,
 started_at timestamptz not null default now(),completed_at timestamptz,status text not null default 'started' check(status in('started','completed','rejected'))
);
create table if not exists public.nextgen_shortlink_campaigns (
 id bigint generated by default as identity primary key,title text not null,provider text not null,target_url text not null,
 revenue_usd numeric(30,8) not null default 0,reward_share_bps int not null default 2000,enabled boolean not null default true
);
create table if not exists public.nextgen_shortlink_completions (
 id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,
 campaign_id bigint not null references public.nextgen_shortlink_campaigns(id),external_reference text unique not null,
 reward_diamond numeric(30,8) not null default 0,status text not null default 'pending' check(status in('pending','posted','reversed','rejected')),
 created_at timestamptz not null default now()
);
create table if not exists public.nextgen_offer_providers (
 id bigint generated by default as identity primary key,provider_key text unique not null,display_name text not null,enabled boolean not null default true
);
create table if not exists public.nextgen_offers (
 id bigint generated by default as identity primary key,provider_id bigint references public.nextgen_offer_providers(id),external_offer_id text not null,
 title text not null,description text,target_url text not null,revenue_usd numeric(30,8) not null default 0,reward_share_bps int not null default 2500,enabled boolean not null default true,
 unique(provider_id,external_offer_id)
);
create table if not exists public.nextgen_offer_completions (
 id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,offer_id bigint not null references public.nextgen_offers(id),
 external_reference text unique not null,status text not null default 'pending' check(status in('pending','posted','reversed','rejected')),revenue_usd numeric(30,8) not null default 0,reward_diamond numeric(30,8) not null default 0,created_at timestamptz not null default now()
);
create table if not exists public.nextgen_quests (
 id bigint generated by default as identity primary key,quest_key text unique not null,title text not null,description text not null,target_count numeric not null default 1,
 reward_diamond numeric(30,8) not null default 0,period text not null default 'daily',enabled boolean not null default true
);
create table if not exists public.nextgen_user_quests (
 user_id uuid not null references auth.users(id) on delete cascade,quest_id bigint not null references public.nextgen_quests(id) on delete cascade,period_key text not null,
 progress numeric not null default 0,claimed_at timestamptz,primary key(user_id,quest_id,period_key)
);
create table if not exists public.nextgen_referrals (
 id bigint generated by default as identity primary key,referrer_user_id uuid not null references auth.users(id) on delete cascade,referred_user_id uuid not null unique references auth.users(id) on delete cascade,
 referral_code text not null,status text not null default 'pending',total_reward_diamond numeric(30,8) not null default 0,created_at timestamptz not null default now()
);

alter table public.nextgen_wallets enable row level security; alter table public.nextgen_miner_catalog enable row level security; alter table public.nextgen_miner_levels enable row level security; alter table public.nextgen_user_miners enable row level security;
alter table public.nextgen_transactions enable row level security; alter table public.nextgen_deposits enable row level security; alter table public.nextgen_withdrawals enable row level security; alter table public.nextgen_reward_ledger enable row level security;
alter table public.nextgen_faucet_claims enable row level security; alter table public.nextgen_ptc_campaigns enable row level security; alter table public.nextgen_ptc_sessions enable row level security; alter table public.nextgen_shortlink_campaigns enable row level security; alter table public.nextgen_shortlink_completions enable row level security;
alter table public.nextgen_offer_providers enable row level security; alter table public.nextgen_offers enable row level security; alter table public.nextgen_offer_completions enable row level security;
alter table public.nextgen_quests enable row level security; alter table public.nextgen_user_quests enable row level security; alter table public.nextgen_referrals enable row level security;

do $$ begin
 create policy "catalog_read" on public.nextgen_miner_catalog for select to authenticated using(enabled=true);
 create policy "levels_read" on public.nextgen_miner_levels for select to authenticated using(true);
 create policy "wallet_self" on public.nextgen_wallets for select to authenticated using((select auth.uid())=user_id);
 create policy "user_miners_self" on public.nextgen_user_miners for select to authenticated using((select auth.uid())=user_id);
 create policy "transactions_self" on public.nextgen_transactions for select to authenticated using((select auth.uid())=user_id);
 create policy "deposits_self" on public.nextgen_deposits for select to authenticated using((select auth.uid())=user_id);
 create policy "withdrawals_self" on public.nextgen_withdrawals for select to authenticated using((select auth.uid())=user_id);
 create policy "rewards_self" on public.nextgen_reward_ledger for select to authenticated using((select auth.uid())=user_id);
 create policy "faucet_self" on public.nextgen_faucet_claims for select to authenticated using((select auth.uid())=user_id);
 create policy "ptc_read" on public.nextgen_ptc_campaigns for select to authenticated using(enabled=true);
 create policy "ptc_sessions_self" on public.nextgen_ptc_sessions for select to authenticated using((select auth.uid())=user_id);
 create policy "shortlink_read" on public.nextgen_shortlink_campaigns for select to authenticated using(enabled=true);
 create policy "shortlink_self" on public.nextgen_shortlink_completions for select to authenticated using((select auth.uid())=user_id);
 create policy "offer_provider_read" on public.nextgen_offer_providers for select to authenticated using(enabled=true);
 create policy "offer_read" on public.nextgen_offers for select to authenticated using(enabled=true);
 create policy "offer_comp_self" on public.nextgen_offer_completions for select to authenticated using((select auth.uid())=user_id);
 create policy "quest_read" on public.nextgen_quests for select to authenticated using(enabled=true);
 create policy "user_quest_self" on public.nextgen_user_quests for select to authenticated using((select auth.uid())=user_id);
 create policy "referrals_self" on public.nextgen_referrals for select to authenticated using((select auth.uid())=referrer_user_id or (select auth.uid())=referred_user_id);
exception when duplicate_object then null; end $$;

create or replace function public.nextgen_upgrade_miner(p_user_miner_id bigint)
returns jsonb language plpgsql security definer set search_path=public as $$
declare uid uuid := auth.uid(); um nextgen_user_miners%rowtype; lvl nextgen_miner_levels%rowtype; w nextgen_wallets%rowtype;
begin
 if uid is null then raise exception 'AUTH_REQUIRED'; end if;
 select * into um from nextgen_user_miners where id=p_user_miner_id and user_id=uid for update;
 if not found then raise exception 'MINER_NOT_FOUND'; end if;
 if um.current_level>=10 then raise exception 'MAX_LEVEL'; end if;
 select * into lvl from nextgen_miner_levels where miner_id=um.miner_id and level=um.current_level+1;
 select * into w from nextgen_wallets where user_id=uid for update;
 if not found then raise exception 'WALLET_NOT_FOUND'; end if;
 if w.diamond_balance<lvl.upgrade_price_diamond then raise exception 'INSUFFICIENT_DIAMOND'; end if;
 update nextgen_wallets set diamond_balance=diamond_balance-lvl.upgrade_price_diamond,updated_at=now() where user_id=uid;
 update nextgen_user_miners set current_level=lvl.level,total_spent_diamond=total_spent_diamond+lvl.upgrade_price_diamond,last_upgrade_at=now() where id=um.id;
 insert into nextgen_transactions(user_id,tx_type,diamond_delta,reference_id,note) values(uid,'miner_upgrade',-lvl.upgrade_price_diamond,p_user_miner_id::text,'Miner Level upgrade');
 return jsonb_build_object('ok',true,'level',lvl.level,'hashrate',lvl.hashrate,'upgrade_price_diamond',lvl.upgrade_price_diamond);
end $$;
revoke all on function public.nextgen_upgrade_miner(bigint) from public,anon; grant execute on function public.nextgen_upgrade_miner(bigint) to authenticated;

insert into public.nextgen_miner_catalog(slug,name,tier,base_hashrate,base_price_diamond,image_path,sort_order)
values
('starter-keyboard','Starter Keyboard','Starter',5,0,'/assets/miners/starter-keyboard.webp',1),
('basic-cpu','Basic CPU','Common',20,500,'/assets/miners/basic-cpu.webp',2),
('entry-gpu','Entry GPU','Common',60,1000,'/assets/miners/entry-gpu.webp',3),
('mini-rig','Mini Rig','Uncommon',150,2500,'/assets/miners/mini-rig.webp',4),
('gaming-pc','Gaming PC','Rare',450,7500,'/assets/miners/gaming-pc.webp',5),
('performance-rig','Performance Rig','Rare',850,15000,'/assets/miners/performance-rig.webp',6),
('hydro-rig','Hydro Rig','Epic',2000,30000,'/assets/miners/hydro-rig.webp',7),
('quantum-rig','Quantum Rig','Epic',4500,60000,'/assets/miners/quantum-rig.webp',8),
('titan-rig','Titan Rig','Legendary',12000,120000,'/assets/miners/titan-rig.webp',9),
('nebula-station','Nebula Station','Legendary',25000,250000,'/assets/miners/nebula-station.webp',10),
('orion-core','Orion Core','Mythic',50000,500000,'/assets/miners/orion-core.webp',11),
('nuclear-reactor','Nuclear Reactor','Mythic',100000,1000000,'/assets/miners/nuclear-reactor.webp',12)
on conflict (slug) do update set name=excluded.name,tier=excluded.tier,base_hashrate=excluded.base_hashrate,base_price_diamond=excluded.base_price_diamond,image_path=excluded.image_path,sort_order=excluded.sort_order,enabled=true;

insert into public.nextgen_miner_levels(miner_id,level,hashrate,upgrade_price_diamond,cumulative_price_diamond)
select m.id,g.level,
       round((m.base_hashrate * power(1.15::numeric,g.level-1))::numeric,2),
       case when g.level=1 then 0::numeric else round((case when m.base_price_diamond=0 then 100 else m.base_price_diamond*0.25 end * power(1.35::numeric,g.level-2))::numeric,0) end,
       case when g.level=1 then 0::numeric else round((case when m.base_price_diamond=0 then 100 else m.base_price_diamond*0.25 end * ((power(1.35::numeric,g.level-1)-1)/0.35))::numeric,0) end
from public.nextgen_miner_catalog m cross join generate_series(1,10) g(level)
on conflict (miner_id,level) do update set hashrate=excluded.hashrate,upgrade_price_diamond=excluded.upgrade_price_diamond,cumulative_price_diamond=excluded.cumulative_price_diamond;

insert into public.nextgen_quests(quest_key,title,description,target_count,reward_diamond)
values
('faucet_20','Faucet Runner','Claim from the faucet 20 times.',20,100),
('offer_5','Offer Explorer','Complete 5 verified offers.',5,250),
('ptc_100','PTC Pilot','Complete 100 verified PTC views.',100,300),
('shortlink_10','Link Runner','Complete 10 verified shortlinks.',10,200)
on conflict (quest_key) do update set title=excluded.title,description=excluded.description,target_count=excluded.target_count,reward_diamond=excluded.reward_diamond,enabled=true;

create or replace function public.nextgen_purchase_miner(p_miner_id bigint)
returns jsonb language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); m nextgen_miner_catalog%rowtype; w nextgen_wallets%rowtype; new_id bigint;
begin
 if uid is null then raise exception 'AUTH_REQUIRED'; end if;
 select * into m from nextgen_miner_catalog where id=p_miner_id and enabled=true for update;
 if not found then raise exception 'MINER_NOT_FOUND'; end if;
 if exists(select 1 from nextgen_user_miners where user_id=uid and miner_id=p_miner_id) then raise exception 'ALREADY_OWNED'; end if;
 if m.base_price_diamond>0 then
   select * into w from nextgen_wallets where user_id=uid for update;
   if not found or w.diamond_balance<m.base_price_diamond then raise exception 'INSUFFICIENT_DIAMOND'; end if;
   update nextgen_wallets set diamond_balance=diamond_balance-m.base_price_diamond,updated_at=now() where user_id=uid;
 else
   if exists(select 1 from nextgen_user_miners where user_id=uid and miner_id=p_miner_id) then raise exception 'STARTER_ALREADY_CLAIMED'; end if;
 end if;
 insert into nextgen_user_miners(user_id,miner_id,current_level,total_spent_diamond) values(uid,p_miner_id,1,m.base_price_diamond) returning id into new_id;
 insert into nextgen_transactions(user_id,tx_type,diamond_delta,reference_id,note) values(uid,'miner_purchase',-m.base_price_diamond,new_id::text,'Miner activation');
 return jsonb_build_object('ok',true,'user_miner_id',new_id,'miner_id',p_miner_id,'level',1,'hashrate',m.base_hashrate);
end $$;
revoke all on function public.nextgen_purchase_miner(bigint) from public,anon; grant execute on function public.nextgen_purchase_miner(bigint) to authenticated;
