-- CP22 — Starter/Free Mining Reserve + Live Accrual + 24h Recharge Enforcement
-- Production migration. Landing page remains untouched.

create table if not exists public.nextgen_starter_mining_settings (
  id boolean primary key default true,
  enabled boolean not null default true,
  asset text not null default 'USDT',
  campaign_key text not null default 'launch-entry-gpu',
  max_free_users integer not null default 1000 check (max_free_users > 0),
  entry_gpu_hashrate numeric(30,8) not null default 60 check (entry_gpu_hashrate >= 0),
  fallback_basic_cpu_hashrate numeric(30,8) not null default 20 check (fallback_basic_cpu_hashrate >= 0),
  target_reward_usd_per_1000_hash_day numeric(30,18) not null default 0.08 check (target_reward_usd_per_1000_hash_day >= 0),
  target_daily_per_entry_gpu_usd numeric(30,18) not null default 0.0048 check (target_daily_per_entry_gpu_usd >= 0),
  target_coverage_days numeric(20,4) not null default 30 check (target_coverage_days > 0),
  minimum_coverage_days numeric(20,4) not null default 7 check (minimum_coverage_days > 0),
  warning_coverage_days numeric(20,4) not null default 14 check (warning_coverage_days > 0),
  reserve_balance_usd numeric(30,18) not null default 0 check (reserve_balance_usd >= 0),
  settled_out_usd numeric(30,18) not null default 0 check (settled_out_usd >= 0),
  updated_at timestamptz not null default now()
);

insert into public.nextgen_starter_mining_settings(id) values(true)
on conflict(id) do nothing;

alter table public.nextgen_starter_mining_settings enable row level security;
revoke all on public.nextgen_starter_mining_settings from anon, authenticated;
revoke all on public.nextgen_starter_mining_settings from public;

-- Dedicated append-only-like reserve ledger for starter promotions.
create table if not exists public.nextgen_starter_reserve_ledger (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('FUND','SETTLE','RELEASE','ADJUSTMENT')),
  event_amount_usd numeric(30,18) not null check (event_amount_usd > 0),
  balance_after_usd numeric(30,18) not null check (balance_after_usd >= 0),
  user_id uuid null,
  user_miner_id bigint null,
  asset text not null default 'USDT',
  source_reference text null,
  note text null,
  created_at timestamptz not null default now()
);
create index if not exists idx_nextgen_starter_reserve_ledger_created on public.nextgen_starter_reserve_ledger(created_at desc);
create index if not exists idx_nextgen_starter_reserve_ledger_user on public.nextgen_starter_reserve_ledger(user_id,created_at desc);
alter table public.nextgen_starter_reserve_ledger enable row level security;
revoke all on public.nextgen_starter_reserve_ledger from anon, authenticated;
revoke all on public.nextgen_starter_reserve_ledger from public;

-- Per-user/per-miner settlement ledger. This is the authoritative bridge between
-- server-side live accrual and actual crypto balance credit.
create table if not exists public.nextgen_starter_mining_settlements (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  user_miner_id bigint not null,
  asset text not null default 'USDT',
  period_start timestamptz not null,
  period_end timestamptz not null,
  elapsed_seconds numeric(30,3) not null check (elapsed_seconds > 0),
  hashrate numeric(30,8) not null check (hashrate >= 0),
  reward_rate_usd_per_hash_second numeric(30,24) not null check (reward_rate_usd_per_hash_second >= 0),
  allocated_usd numeric(30,18) not null check (allocated_usd >= 0),
  crypto_amount numeric(60,24) not null check (crypto_amount >= 0),
  created_at timestamptz not null default now(),
  unique(user_id,user_miner_id,asset,period_start,period_end)
);
create index if not exists idx_nextgen_starter_settlements_user on public.nextgen_starter_mining_settlements(user_id,created_at desc);
create index if not exists idx_nextgen_starter_settlements_period on public.nextgen_starter_mining_settlements(period_end desc);
alter table public.nextgen_starter_mining_settlements enable row level security;
revoke all on public.nextgen_starter_mining_settlements from anon, authenticated;
revoke all on public.nextgen_starter_mining_settlements from public;

-- Make the existing per-miner accrual cursor suitable for the starter engine.
-- The existing column already exists and is server-controlled through SECURITY DEFINER functions.

create or replace function public.nextgen_starter_capacity_snapshot()
returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare
  s public.nextgen_starter_mining_settings%rowtype;
  active_users integer := 0;
  active_miners integer := 0;
  active_free_weight numeric := 0;
  daily_target numeric := 0;
  coverage_days numeric := 0;
  target_reserve numeric := 0;
  minimum_reserve numeric := 0;
  multiplier numeric := 0;
  status text := 'PAUSED';
  claimed_slots integer := 0;
  remaining_slots integer := 0;
begin
  if not public.nextgen_is_owner() then raise exception 'OWNER_ONLY'; end if;
  select * into s from public.nextgen_starter_mining_settings where id=true for update;
  select count(distinct um.user_id),count(*) into active_users,active_miners
  from public.nextgen_user_miners um
  where um.reward_class='free_bonus' and um.is_merged=false and um.status='active' and um.recharge_expires_at>now();
  select coalesce(sum(l.hashrate*greatest(l.efficiency,0)*least(greatest(coalesce(um.energy_percent,0),0),100)/100.0),0)
    into active_free_weight
  from public.nextgen_user_miners um
  join public.nextgen_miner_levels l on l.miner_id=um.miner_id and l.level=um.current_level
  where um.reward_class='free_bonus' and um.is_merged=false and um.status='active' and um.recharge_expires_at>now();
  daily_target := active_free_weight*(s.target_reward_usd_per_1000_hash_day/1000.0);
  target_reserve := daily_target*s.target_coverage_days;
  minimum_reserve := daily_target*s.minimum_coverage_days;
  coverage_days := case when daily_target>0 then s.reserve_balance_usd/daily_target else 999999 end;
  multiplier := case when target_reserve<=0 then 1 else least(greatest(s.reserve_balance_usd/target_reserve,0),1) end;
  status := case
    when not s.enabled then 'DISABLED'
    when active_users=0 then 'IDLE'
    when s.reserve_balance_usd<=0 then 'PAUSED_NO_RESERVE'
    when coverage_days < s.minimum_coverage_days then 'CAPACITY_GUARDED'
    when coverage_days < s.warning_coverage_days then 'WARNING'
    else 'HEALTHY'
  end;
  select coalesce(c.claimed_slots,0),greatest(coalesce(c.total_slots,0)-coalesce(c.claimed_slots,0),0)
    into claimed_slots,remaining_slots
  from public.nextgen_registration_bonus_campaigns c where c.campaign_key=s.campaign_key;
  return jsonb_build_object(
    'enabled',s.enabled,
    'asset',s.asset,
    'campaign_key',s.campaign_key,
    'max_free_users',s.max_free_users,
    'claimed_slots',claimed_slots,
    'remaining_slots',remaining_slots,
    'active_free_users',active_users,
    'active_free_miners',active_miners,
    'active_free_weighted_hash',active_free_weight,
    'target_daily_liability_usd',daily_target,
    'target_30d_reserve_usd',target_reserve,
    'minimum_7d_reserve_usd',minimum_reserve,
    'reserve_balance_usd',s.reserve_balance_usd,
    'settled_out_usd',s.settled_out_usd,
    'coverage_days',coverage_days,
    'capacity_multiplier',multiplier,
    'status',status,
    'target_reward_usd_per_1000_hash_day',s.target_reward_usd_per_1000_hash_day,
    'target_daily_per_entry_gpu_usd',s.target_daily_per_entry_gpu_usd,
    'target_coverage_days',s.target_coverage_days,
    'warning_coverage_days',s.warning_coverage_days,
    'minimum_coverage_days',s.minimum_coverage_days,
    'as_of',now()
  );
end;
$$;
revoke all on function public.nextgen_starter_capacity_snapshot() from public,anon;
grant execute on function public.nextgen_starter_capacity_snapshot() to authenticated;

create or replace function public.nextgen_owner_fund_starter_reserve(p_amount_usd numeric, p_note text)
returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare
  s public.nextgen_starter_mining_settings%rowtype;
  new_balance numeric;
begin
  if not public.nextgen_is_owner() then raise exception 'OWNER_ONLY'; end if;
  if p_amount_usd is null or p_amount_usd<=0 then raise exception 'INVALID_AMOUNT'; end if;
  if p_note is null or length(trim(p_note))<3 then raise exception 'NOTE_REQUIRED'; end if;
  perform pg_advisory_xact_lock(hashtext('nextgen_starter_reserve'));
  select * into s from public.nextgen_starter_mining_settings where id=true for update;
  new_balance:=s.reserve_balance_usd+p_amount_usd;
  update public.nextgen_starter_mining_settings set reserve_balance_usd=new_balance,updated_at=now() where id=true;
  insert into public.nextgen_starter_reserve_ledger(event_type,event_amount_usd,balance_after_usd,asset,source_reference,note)
  values('FUND',p_amount_usd,new_balance,s.asset,md5('fund:'||now()::text||':'||p_amount_usd::text),left(trim(p_note),500));
  return jsonb_build_object('success',true,'funded_usd',p_amount_usd,'reserve_balance_usd',new_balance);
end;
$$;
revoke all on function public.nextgen_owner_fund_starter_reserve(numeric,text) from public,anon,authenticated;

-- Normalize expired miners immediately. This is called by user-facing snapshots/actions and by cron.
create or replace function public.nextgen_enforce_mining_recharge_state_for_user(p_user_id uuid)
returns integer
language plpgsql
security definer
set search_path to ''
as $$
declare n integer;
begin
  if p_user_id is null then raise exception 'USER_REQUIRED'; end if;
  update public.nextgen_user_miners
  set status='paused'
  where user_id=p_user_id and is_merged=false and status='active' and recharge_expires_at<=now();
  get diagnostics n=row_count;
  return n;
end;
$$;
revoke all on function public.nextgen_enforce_mining_recharge_state_for_user(uuid) from public,anon,authenticated;

create or replace function public.nextgen_enforce_all_mining_recharge_states()
returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare n integer := 0;
begin
  update public.nextgen_user_miners
  set status='paused'
  where is_merged=false and status='active' and recharge_expires_at<=now();
  get diagnostics n=row_count;
  return jsonb_build_object('success',true,'paused_miners',n,'as_of',now());
end;
$$;
revoke all on function public.nextgen_enforce_all_mining_recharge_states() from public,anon,authenticated;

-- Compute a server-side live estimate. It never mutates crypto balances.
create or replace function public.nextgen_live_mining_snapshot(p_asset text default 'USDT')
returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare
  uid uuid:=auth.uid();
  asset_code text:=upper(trim(coalesce(p_asset,'USDT')));
  s public.nextgen_starter_mining_settings%rowtype;
  active_hash numeric:=0; free_hash numeric:=0; standard_hash numeric:=0;
  active_miners integer:=0; free_miners integer:=0; standard_miners integer:=0;
  now_ts timestamptz:=now();
  free_rate numeric:=0; standard_rate numeric:=0; capacity_multiplier numeric:=0;
  remaining_session_seconds numeric:=0; live_elapsed_seconds numeric:=0;
  live_usd numeric:=0; live_crypto numeric:=0; hourly_usd numeric:=0; daily_usd numeric:=0; thirty_day_usd numeric:=0;
  selected_rate numeric:=0; selected_rate_updated timestamptz;
  session_started_at timestamptz; session_expires_at timestamptz;
  status text:='PAUSED'; source text:='NONE';
  starter_daily_liability numeric:=0; starter_coverage_days numeric:=0;
begin
  if uid is null then raise exception 'AUTH_REQUIRED'; end if;
  perform public.nextgen_enforce_mining_recharge_state_for_user(uid);
  select * into s from public.nextgen_starter_mining_settings where id=true;
  select r.rate_usd,r.updated_at into selected_rate,selected_rate_updated
  from public.nextgen_exchange_rates r where upper(r.asset)=asset_code
  order by r.updated_at desc limit 1;

  with active as (
    select um.id,um.reward_class,um.last_recharge_at,um.recharge_expires_at,
           l.hashrate,l.efficiency,least(greatest(coalesce(um.energy_percent,0),0),100) energy_percent,
           greatest(extract(epoch from (least(now_ts,um.recharge_expires_at)-greatest(um.last_recharge_at,now_ts-interval '24 hours'))),0) elapsed_seconds
    from public.nextgen_user_miners um
    join public.nextgen_miner_levels l on l.miner_id=um.miner_id and l.level=um.current_level
    where um.user_id=uid and um.is_merged=false and um.status='active' and um.recharge_expires_at>now_ts
  )
  select count(*)::integer,
         count(*) filter(where reward_class='free_bonus')::integer,
         count(*) filter(where reward_class<>'free_bonus' or reward_class is null)::integer,
         coalesce(sum(hashrate*greatest(efficiency,0)*energy_percent/100.0),0),
         coalesce(sum(hashrate*greatest(efficiency,0)*energy_percent/100.0) filter(where reward_class='free_bonus'),0),
         coalesce(sum(hashrate*greatest(efficiency,0)*energy_percent/100.0) filter(where reward_class<>'free_bonus' or reward_class is null),0),
         min(last_recharge_at),max(recharge_expires_at)
  into active_miners,free_miners,standard_miners,active_hash,free_hash,standard_hash,session_started_at,session_expires_at
  from active;

  capacity_multiplier:=case
    when free_hash<=0 then 0
    when free_hash*(s.target_reward_usd_per_1000_hash_day/1000.0)*s.target_coverage_days<=0 then 1
    else least(greatest(s.reserve_balance_usd/(free_hash*(s.target_reward_usd_per_1000_hash_day/1000.0)*s.target_coverage_days),0),1)
  end;
  starter_daily_liability:=free_hash*(s.target_reward_usd_per_1000_hash_day/1000.0)*capacity_multiplier;
  starter_coverage_days:=case when starter_daily_liability>0 then s.reserve_balance_usd/starter_daily_liability else 999999 end;
  free_rate:=case when free_hash>0 then (s.target_reward_usd_per_1000_hash_day/1000.0/86400.0)*capacity_multiplier else 0 end;
  select coalesce(max(p.reward_rate_usd_per_hash_second),0) into standard_rate
  from public.nextgen_mining_daily_pools p
  where upper(p.asset)=asset_code and p.pool_date=timezone('utc',now())::date and p.mining_budget_usd>0 and p.prepared_at is not null;

  if free_hash>0 and s.enabled and s.reserve_balance_usd>0 then
    select coalesce(sum(x.reward_usd),0),coalesce(sum(x.elapsed_seconds),0)
    into live_usd,live_elapsed_seconds
    from (
      select free_rate*(l.hashrate*greatest(l.efficiency,0)*least(greatest(coalesce(um.energy_percent,0),0),100)/100.0) *
             least(greatest(extract(epoch from (least(now_ts,um.recharge_expires_at)-greatest(um.last_recharge_at,now_ts-interval '24 hours'))),0),86400) reward_usd,
             least(greatest(extract(epoch from (least(now_ts,um.recharge_expires_at)-greatest(um.last_recharge_at,now_ts-interval '24 hours'))),0),86400) elapsed_seconds
      from public.nextgen_user_miners um
      join public.nextgen_miner_levels l on l.miner_id=um.miner_id and l.level=um.current_level
      where um.user_id=uid and um.reward_class='free_bonus' and um.is_merged=false and um.status='active' and um.recharge_expires_at>now_ts
    ) x;
    remaining_session_seconds:=greatest(extract(epoch from (session_expires_at-now_ts)),0);
    if selected_rate>0 then live_crypto:=round(live_usd/selected_rate,24); end if;
    hourly_usd:=free_rate*free_hash*3600;
    daily_usd:=free_rate*free_hash*86400;
    thirty_day_usd:=daily_usd*30;
    status:=case when capacity_multiplier<1 then 'ACTIVE_GUARDED' else 'ACTIVE' end;
    source:='STARTER_RESERVE';
  elsif standard_hash>0 and standard_rate>0 then
    select coalesce(sum(x.reward_usd),0),coalesce(sum(x.elapsed_seconds),0)
    into live_usd,live_elapsed_seconds
    from (
      select standard_rate*(l.hashrate*greatest(l.efficiency,0)*least(greatest(coalesce(um.energy_percent,0),0),100)/100.0) *
             least(greatest(extract(epoch from (least(now_ts,um.recharge_expires_at)-greatest(um.last_recharge_at,now_ts-interval '24 hours'))),0),86400) reward_usd,
             least(greatest(extract(epoch from (least(now_ts,um.recharge_expires_at)-greatest(um.last_recharge_at,now_ts-interval '24 hours'))),0),86400) elapsed_seconds
      from public.nextgen_user_miners um
      join public.nextgen_miner_levels l on l.miner_id=um.miner_id and l.level=um.current_level
      where um.user_id=uid and coalesce(um.reward_class,'standard')<>'free_bonus' and um.is_merged=false and um.status='active' and um.recharge_expires_at>now_ts
    ) x;
    remaining_session_seconds:=greatest(extract(epoch from (session_expires_at-now_ts)),0);
    if selected_rate>0 then live_crypto:=round(live_usd/selected_rate,24); end if;
    hourly_usd:=standard_rate*standard_hash*3600;
    daily_usd:=standard_rate*standard_hash*86400;
    thirty_day_usd:=daily_usd*30;
    status:='ACTIVE_POOL';
    source:='FUNDED_POOL';
  elsif active_miners>0 then
    status:=case when free_hash>0 and s.reserve_balance_usd<=0 then 'STARTER_POOL_PAUSED' else 'POOL_PAUSED' end;
  end if;

  return jsonb_build_object(
    'asset',asset_code,'status',status,'source',source,
    'active_miners',active_miners,'free_miners',free_miners,'standard_miners',standard_miners,
    'active_hashrate',active_hash,'free_hashrate',free_hash,'standard_hashrate',standard_hash,
    'capacity_multiplier',capacity_multiplier,'starter_reserve_balance_usd',s.reserve_balance_usd,
    'starter_daily_liability_usd',starter_daily_liability,'starter_coverage_days',starter_coverage_days,
    'reward_rate_usd_per_hash_second',case when source='STARTER_RESERVE' then free_rate else standard_rate end,
    'hourly_usd',hourly_usd,'daily_usd',daily_usd,'thirty_day_usd',thirty_day_usd,
    'estimated_usd',live_usd,'estimated_crypto',live_crypto,'elapsed_seconds',live_elapsed_seconds,
    'remaining_session_seconds',remaining_session_seconds,'session_started_at',session_started_at,
    'recharge_expires_at',session_expires_at,'crypto_rate_usd',coalesce(selected_rate,0),
    'crypto_rate_updated_at',selected_rate_updated,'claim_is_server_settled',true,'as_of',now_ts
  );
end;
$$;
revoke all on function public.nextgen_live_mining_snapshot(text) from public,anon;
grant execute on function public.nextgen_live_mining_snapshot(text) to authenticated;

-- Realize starter accrual into the crypto ledger. This function settles the interval since
-- last_accrual_at, capped by the miner's 24h recharge expiry. It never fabricates provider revenue.
create or replace function public.nextgen_settle_starter_mining_for_user(p_user_id uuid, p_asset text default 'USDT')
returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare
  uid uuid:=p_user_id;
  asset_code text:=upper(trim(coalesce(p_asset,'USDT')));
  s public.nextgen_starter_mining_settings%rowtype;
  er numeric:=0;
  er_updated timestamptz;
  r record;
  start_ts timestamptz;
  end_ts timestamptz;
  secs numeric;
  rate numeric;
  usd numeric;
  crypto_amt numeric;
  total_usd numeric:=0;
  total_crypto numeric:=0;
  existing_id bigint;
  reserve_after numeric;
  rate_capacity_multiplier numeric:=0;
begin
  if uid is null then raise exception 'USER_REQUIRED'; end if;
  perform pg_advisory_xact_lock(hashtextextended(uid::text||':'||asset_code, 20423));
  select * into s from public.nextgen_starter_mining_settings where id=true for update;
  if not s.enabled or s.asset<>asset_code then return jsonb_build_object('success',true,'settled_usd',0,'settled_crypto',0,'reason','STARTER_DISABLED'); end if;
  select r.rate_usd,r.updated_at into er,er_updated from public.nextgen_exchange_rates r where upper(r.asset)=asset_code order by r.updated_at desc limit 1;
  if er is null or er<=0 or er_updated<now()-interval '15 minutes' then
    return jsonb_build_object('success',true,'settled_usd',0,'settled_crypto',0,'reason','ASSET_RATE_STALE');
  end if;
  for r in
    select um.id,um.user_id,um.last_accrual_at,um.last_recharge_at,um.recharge_expires_at,um.status,
           l.hashrate,l.efficiency,least(greatest(coalesce(um.energy_percent,0),0),100) energy_percent
    from public.nextgen_user_miners um
    join public.nextgen_miner_levels l on l.miner_id=um.miner_id and l.level=um.current_level
    where um.user_id=uid and um.reward_class='free_bonus' and um.is_merged=false
    order by um.id
    for update
  loop
    start_ts:=greatest(coalesce(r.last_accrual_at,r.last_recharge_at),coalesce(r.last_recharge_at,r.last_accrual_at));
    end_ts:=least(now(),r.recharge_expires_at);
    if start_ts is null or end_ts<=start_ts then continue; end if;
    secs:=least(greatest(extract(epoch from (end_ts-start_ts)),0),86400);
    -- Rate is capacity-aware and matches the live snapshot. Full target rate requires the
    -- configured target reserve; lower funded coverage transparently throttles the starter rate.
    rate:=(s.target_reward_usd_per_1000_hash_day/1000.0/86400.0);
    select least(greatest(s.reserve_balance_usd / nullif(
      (select coalesce(sum(l2.hashrate*greatest(l2.efficiency,0)*least(greatest(coalesce(um2.energy_percent,0),0),100)/100.0),0)
       from public.nextgen_user_miners um2
       join public.nextgen_miner_levels l2 on l2.miner_id=um2.miner_id and l2.level=um2.current_level
       where um2.reward_class='free_bonus' and um2.is_merged=false
         and um2.status='active' and um2.recharge_expires_at>now()),0)
      * (s.target_reward_usd_per_1000_hash_day/1000.0) * s.target_coverage_days,0),0),1)
      into rate_capacity_multiplier;
    rate:=rate*coalesce(rate_capacity_multiplier,0);
    usd:=round(rate*r.hashrate*greatest(r.efficiency,0)*r.energy_percent/100.0*secs,18);
    if usd<=0 then update public.nextgen_user_miners set last_accrual_at=end_ts where id=r.id; continue; end if;
    if usd>s.reserve_balance_usd-total_usd then usd:=greatest(s.reserve_balance_usd-total_usd,0); end if;
    if usd<=0 then exit; end if;
    crypto_amt:=round(usd/er,24);
    select id into existing_id from public.nextgen_starter_mining_settlements x where x.user_id=uid and x.user_miner_id=r.id and x.asset=asset_code and x.period_start=start_ts and x.period_end=end_ts;
    if existing_id is null then
      insert into public.nextgen_starter_mining_settlements(user_id,user_miner_id,asset,period_start,period_end,elapsed_seconds,hashrate,reward_rate_usd_per_hash_second,allocated_usd,crypto_amount)
      values(uid,r.id,asset_code,start_ts,end_ts,secs,r.hashrate,rate,usd,crypto_amt);
      insert into public.nextgen_crypto_balances(user_id,asset,balance,reserved_balance)
      values(uid,asset_code,crypto_amt,0)
      on conflict(user_id,asset) do update set balance=public.nextgen_crypto_balances.balance+excluded.balance,updated_at=now();
      insert into public.nextgen_crypto_ledger(user_id,asset,direction,amount,usd_value,reference_type,reference_id,note)
      values(uid,asset_code,'mining_reward',crypto_amt,usd,'starter_mining',r.id::text,'24h starter mining accrual settlement');
      insert into public.nextgen_transactions(user_id,tx_type,diamond_delta,usd_delta,asset,crypto_amount,reference_id,note)
      values(uid,'starter_mining_reward',0,usd,asset_code,crypto_amt,r.id::text,'Starter reserve mining settlement');
      insert into public.nextgen_starter_reserve_ledger(event_type,event_amount_usd,balance_after_usd,user_id,user_miner_id,asset,source_reference,note)
      values('SETTLE',usd,greatest(s.reserve_balance_usd-total_usd-usd,0),uid,r.id,asset_code,md5('starter_settle:'||uid::text||':'||r.id::text||':'||start_ts::text||':'||end_ts::text),'Starter mining payout reserve release');
      total_usd:=total_usd+usd;
      total_crypto:=total_crypto+crypto_amt;
    end if;
    update public.nextgen_user_miners set last_accrual_at=end_ts where id=r.id;
  end loop;
  if total_usd>0 then
    reserve_after:=greatest(s.reserve_balance_usd-total_usd,0);
    update public.nextgen_starter_mining_settings set reserve_balance_usd=reserve_after,settled_out_usd=settled_out_usd+total_usd,updated_at=now() where id=true;
  end if;
  return jsonb_build_object('success',true,'asset',asset_code,'settled_usd',total_usd,'settled_crypto',total_crypto,'reserve_balance_usd',case when total_usd>0 then greatest(s.reserve_balance_usd-total_usd,0) else s.reserve_balance_usd end,'rate_usd',er,'rate_updated_at',er_updated);
end;
$$;
revoke all on function public.nextgen_settle_starter_mining_for_user(uuid,text) from public,anon,authenticated;

create or replace function public.nextgen_process_starter_mining_expired()
returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare
  u uuid;
  settled_users integer:=0;
  settled_usd numeric:=0;
  paused_miners integer:=0;
  x jsonb;
begin
  for u in select distinct user_id from public.nextgen_user_miners where reward_class='free_bonus' and is_merged=false and recharge_expires_at<=now() loop
    x:=public.nextgen_settle_starter_mining_for_user(u,'USDT');
    settled_users:=settled_users+1;
    settled_usd:=settled_usd+coalesce((x->>'settled_usd')::numeric,0);
    paused_miners:=paused_miners+public.nextgen_enforce_mining_recharge_state_for_user(u);
  end loop;
  return jsonb_build_object('success',true,'users_processed',settled_users,'settled_usd',settled_usd,'paused_miners',paused_miners,'as_of',now());
end;
$$;
revoke all on function public.nextgen_process_starter_mining_expired() from public,anon,authenticated;

create or replace function public.nextgen_assert_starter_capacity_for_recharge(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path to ''
as $$
declare
  s public.nextgen_starter_mining_settings%rowtype;
  active_weight numeric:=0;
  projected_daily numeric:=0;
  minimum_reserve numeric:=0;
begin
  if p_user_id is null then raise exception 'USER_REQUIRED'; end if;
  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text||':starter_recharge',20424));
  select * into s from public.nextgen_starter_mining_settings where id=true for update;
  if not s.enabled then raise exception 'STARTER_MINING_DISABLED'; end if;
  if not exists (select 1 from public.nextgen_user_miners where user_id=p_user_id and reward_class='free_bonus' and is_merged=false) then return; end if;
  select coalesce(sum(l.hashrate*greatest(l.efficiency,0)*least(greatest(coalesce(um.energy_percent,0),0),100)/100.0),0)
    into active_weight
  from public.nextgen_user_miners um
  join public.nextgen_miner_levels l on l.miner_id=um.miner_id and l.level=um.current_level
  where um.reward_class='free_bonus' and um.is_merged=false and um.user_id=p_user_id;
  projected_daily:=active_weight*(s.target_reward_usd_per_1000_hash_day/1000.0);
  minimum_reserve:=projected_daily*s.minimum_coverage_days;
  if s.reserve_balance_usd < minimum_reserve then
    raise exception 'STARTER_CAPACITY_BLOCKED';
  end if;
end;
$$;
revoke all on function public.nextgen_assert_starter_capacity_for_recharge(uuid) from public,anon,authenticated;

-- Safely wrap the existing recharge/check-in flows so starter accrual is realized before renewal.
alter function public.nextgen_recharge_hashrate() rename to nextgen_recharge_hashrate_legacy_cp22;
create or replace function public.nextgen_recharge_hashrate()
returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare uid uuid:=auth.uid(); x jsonb; r jsonb;
begin
  if uid is null then raise exception 'AUTH_REQUIRED'; end if;
  perform public.nextgen_settle_starter_mining_for_user(uid,'USDT');
  perform public.nextgen_assert_starter_capacity_for_recharge(uid);
  r:=public.nextgen_recharge_hashrate_legacy_cp22();
  perform public.nextgen_enforce_mining_recharge_state_for_user(uid);
  return r;
end;
$$;
revoke all on function public.nextgen_recharge_hashrate_legacy_cp22() from public,anon,authenticated;
revoke all on function public.nextgen_recharge_hashrate() from public,anon;
grant execute on function public.nextgen_recharge_hashrate() to authenticated;

-- Wrap daily check-in so its built-in 24h renewal cannot discard a starter accrual interval.
alter function public.nextgen_claim_daily_checkin() rename to nextgen_claim_daily_checkin_legacy_cp22;
create or replace function public.nextgen_claim_daily_checkin()
returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare uid uuid:=auth.uid(); r jsonb; s jsonb;
begin
  if uid is null then raise exception 'AUTH_REQUIRED'; end if;
  s:=public.nextgen_settle_starter_mining_for_user(uid,'USDT');
  r:=public.nextgen_claim_daily_checkin_legacy_cp22();
  return r || jsonb_build_object('starter_settled_usd',coalesce(s->'settled_usd','0'::jsonb),'starter_settled_crypto',coalesce(s->'settled_crypto','0'::jsonb));
end;
$$;
revoke all on function public.nextgen_claim_daily_checkin_legacy_cp22() from public,anon,authenticated;
revoke all on function public.nextgen_claim_daily_checkin() from public,anon;
grant execute on function public.nextgen_claim_daily_checkin() to authenticated;

-- Wrap the existing Farm snapshot to preserve its current contract while adding authoritative live data.
alter function public.nextgen_farm_snapshot(text) rename to nextgen_farm_snapshot_legacy_cp22;
create or replace function public.nextgen_farm_snapshot(p_asset text default 'USDT')
returns jsonb
language plpgsql
volatile security definer
set search_path to ''
as $$
declare
  uid uuid:=auth.uid();
  base jsonb;
  live jsonb;
  legacy_expiry timestamptz;
  live_status text;
begin
  if uid is null then raise exception 'AUTH_REQUIRED'; end if;
  perform public.nextgen_enforce_mining_recharge_state_for_user(uid);
  base:=public.nextgen_farm_snapshot_legacy_cp22(p_asset);
  live:=public.nextgen_live_mining_snapshot(p_asset);
  legacy_expiry:=nullif(live->>'recharge_expires_at','')::timestamptz;
  live_status:=coalesce(live->>'status','PAUSED');
  return base || jsonb_build_object(
    'live_earnings',jsonb_build_object(
      'status',live_status,
      'estimated_usd',coalesce((live->>'estimated_usd')::numeric,0),
      'estimated_crypto',coalesce((live->>'estimated_crypto')::numeric,0),
      'elapsed_seconds',coalesce((live->>'elapsed_seconds')::numeric,0),
      'currency',upper(trim(coalesce(p_asset,'USDT'))),
      'claim_is_server_settled',true,
      'source',coalesce(live->>'source','NONE'),
      'hourly_usd',coalesce((live->>'hourly_usd')::numeric,0),
      'daily_usd',coalesce((live->>'daily_usd')::numeric,0),
      'thirty_day_usd',coalesce((live->>'thirty_day_usd')::numeric,0),
      'reward_rate_usd_per_hash_second',coalesce((live->>'reward_rate_usd_per_hash_second')::numeric,0),
      'crypto_rate_usd',coalesce((live->>'crypto_rate_usd')::numeric,0),
      'as_of',coalesce((live->>'as_of')::timestamptz,now()),
      'capacity_multiplier',coalesce((live->>'capacity_multiplier')::numeric,0),
      'starter_reserve_balance_usd',coalesce((live->>'starter_reserve_balance_usd')::numeric,0),
      'starter_coverage_days',coalesce((live->>'starter_coverage_days')::numeric,0),
      'recharge_expires_at',legacy_expiry
    ),
    'hashrate_status',jsonb_build_object(
      'status',live_status,
      'recharge_expires_at',legacy_expiry,
      'premium',coalesce((base->'hashrate_status'->>'premium')::boolean,false),
      'membership_expires_at',base->'hashrate_status'->'membership_expires_at'
    )
  );
end;
$$;
revoke all on function public.nextgen_farm_snapshot_legacy_cp22(text) from public,anon,authenticated;
revoke all on function public.nextgen_farm_snapshot(text) from public,anon;
grant execute on function public.nextgen_farm_snapshot(text) to authenticated;

-- Owner-only admin snapshot aliases.
create or replace function public.nextgen_owner_starter_mining_dashboard()
returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare cap jsonb; settled_today numeric:=0; settled_30d numeric:=0; active_cycles integer:=0; paused_cycles integer:=0; expired_unsettled integer:=0;
begin
  if not public.nextgen_is_owner() then raise exception 'OWNER_ONLY'; end if;
  cap:=public.nextgen_starter_capacity_snapshot();
  select coalesce(sum(event_amount_usd),0) into settled_today from public.nextgen_starter_reserve_ledger where event_type='SETTLE' and created_at::date=timezone('utc',now())::date;
  select coalesce(sum(event_amount_usd),0) into settled_30d from public.nextgen_starter_reserve_ledger where event_type='SETTLE' and created_at>=now()-interval '30 days';
  select count(*) filter(where um.status='active' and um.recharge_expires_at>now()),count(*) filter(where um.status='paused' and um.recharge_expires_at<=now()),count(*) filter(where um.status='paused' and um.last_accrual_at<um.recharge_expires_at)
    into active_cycles,paused_cycles,expired_unsettled
  from public.nextgen_user_miners um where um.reward_class='free_bonus' and um.is_merged=false;
  return cap || jsonb_build_object('settled_today_usd',settled_today,'settled_30d_usd',settled_30d,'active_cycles',active_cycles,'paused_cycles',paused_cycles,'expired_unsettled_cycles',expired_unsettled);
end;
$$;
revoke all on function public.nextgen_owner_starter_mining_dashboard() from public,anon,authenticated;
revoke execute on function public.nextgen_owner_starter_mining_dashboard() from anon,authenticated;

-- Free-bonus upgrades must not bypass starter reserve capacity.
create or replace function public.nextgen_assert_starter_capacity_for_expansion(p_additional_daily_usd numeric)
returns void
language plpgsql
security definer
set search_path to ''
as $$
declare s public.nextgen_starter_mining_settings%rowtype; active_weight numeric:=0; projected numeric; min_reserve numeric;
begin
  if p_additional_daily_usd is null or p_additional_daily_usd<=0 then return; end if;
  perform pg_advisory_xact_lock(hashtext('nextgen_starter_reserve'));
  select * into s from public.nextgen_starter_mining_settings where id=true for update;
  if not s.enabled then raise exception 'STARTER_MINING_DISABLED'; end if;
  select coalesce(sum(l.hashrate*greatest(l.efficiency,0)*least(greatest(coalesce(um.energy_percent,0),0),100)/100.0),0)
    into active_weight
  from public.nextgen_user_miners um join public.nextgen_miner_levels l on l.miner_id=um.miner_id and l.level=um.current_level
  where um.reward_class='free_bonus' and um.is_merged=false and um.status='active' and um.recharge_expires_at>now();
  projected:=active_weight*(s.target_reward_usd_per_1000_hash_day/1000.0)+p_additional_daily_usd;
  min_reserve:=projected*s.minimum_coverage_days;
  if s.reserve_balance_usd < min_reserve then raise exception 'STARTER_CAPACITY_BLOCKED'; end if;
end;
$$;
revoke all on function public.nextgen_assert_starter_capacity_for_expansion(numeric) from public,anon,authenticated;

-- Trigger hardens free-bonus level expansion without rewriting existing upgrade/merge functions.
create or replace function public.nextgen_guard_free_bonus_upgrade_trigger()
returns trigger
language plpgsql
security definer
set search_path to ''
as $$
declare old_hash numeric; new_hash numeric; add_daily numeric;
begin
  if coalesce(OLD.reward_class,'standard')='free_bonus' and coalesce(NEW.current_level,OLD.current_level)>OLD.current_level then
    select hashrate into old_hash from public.nextgen_miner_levels where miner_id=OLD.miner_id and level=OLD.current_level;
    select hashrate into new_hash from public.nextgen_miner_levels where miner_id=NEW.miner_id and level=NEW.current_level;
    add_daily:=greatest(new_hash-old_hash,0)*(0.08/1000.0);
    if add_daily>0 then perform public.nextgen_assert_starter_capacity_for_expansion(add_daily); end if;
  end if;
  return NEW;
end;
$$;
revoke all on function public.nextgen_guard_free_bonus_upgrade_trigger() from public,anon,authenticated;
drop trigger if exists trg_nextgen_free_bonus_capacity on public.nextgen_user_miners;
create trigger trg_nextgen_free_bonus_capacity
before update of current_level on public.nextgen_user_miners
for each row execute function public.nextgen_guard_free_bonus_upgrade_trigger();

-- Give every existing free-bonus miner an explicit 24h activation cursor from its current recharge window.
update public.nextgen_user_miners
set last_recharge_at=coalesce(last_recharge_at,activated_at,now()),
    recharge_expires_at=coalesce(recharge_expires_at,coalesce(last_recharge_at,activated_at,now())+interval '24 hours'),
    last_accrual_at=least(coalesce(last_accrual_at,recharge_expires_at),recharge_expires_at)
where reward_class='free_bonus' and is_merged=false;

-- Keep the legacy configured cap aligned with the new starter target; actual funding remains a separate reserve.
update public.nextgen_mining_economy_settings
set free_daily_cap_usd=0.0048,updated_at=now()
where id=true;

-- Deterministic 1..1001 economic E2E test. It is owner-only and uses temporary rows only.
create or replace function public.nextgen_owner_starter_mining_e2e_1001()
returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare
  s public.nextgen_starter_mining_settings%rowtype;
  slot integer;
  expected_free_daily numeric;
  expected_free_30d numeric;
  expected_basic_daily numeric;
  min_reserve numeric;
  failures text[]:=array[]::text[];
  test_uuid uuid:=gen_random_uuid();
  test_miner bigint;
  before_balance numeric:=0;
  after_balance numeric:=0;
  projection_hourly numeric;
  projection_daily numeric;
  projection_30d numeric;
begin
  if not public.nextgen_is_owner() then raise exception 'OWNER_ONLY'; end if;
  select * into s from public.nextgen_starter_mining_settings where id=true;
  expected_free_daily:=s.entry_gpu_hashrate*(s.target_reward_usd_per_1000_hash_day/1000.0);
  expected_free_30d:=expected_free_daily*30;
  expected_basic_daily:=s.fallback_basic_cpu_hashrate*(s.target_reward_usd_per_1000_hash_day/1000.0);
  min_reserve:=expected_free_daily*s.minimum_coverage_days;

  if expected_free_daily<>0.0048 then failures:=array_append(failures,'ENTRY_GPU_DAILY_TARGET_MISMATCH'); end if;
  if expected_basic_daily<>0.0016 then failures:=array_append(failures,'BASIC_CPU_DAILY_TARGET_MISMATCH'); end if;
  if expected_free_30d<>0.144 then failures:=array_append(failures,'ENTRY_GPU_30D_TARGET_MISMATCH'); end if;
  if s.max_free_users<>1000 then failures:=array_append(failures,'FREE_USER_CAP_MISMATCH'); end if;

  -- Slot allocation contract: 1..1000 Entry GPU, 1001 fallback Basic CPU.
  for slot in 1..1001 loop
    if slot<=1000 then test_miner:=3; else test_miner:=2; end if;
    if slot<=1000 and test_miner<>3 then failures:=array_append(failures,'SLOT_'||slot||'_NOT_ENTRY_GPU'); end if;
    if slot=1001 and test_miner<>2 then failures:=array_append(failures,'SLOT_1001_NOT_BASIC_CPU'); end if;
  end loop;

  projection_hourly:=expected_free_daily/24;
  projection_daily:=projection_hourly*24;
  projection_30d:=projection_daily*30;
  if abs(projection_hourly-0.0002)>0.0000000001 then failures:=array_append(failures,'HOURLY_PROJECTION_MISMATCH'); end if;
  if abs(projection_daily-0.0048)>0.0000000001 then failures:=array_append(failures,'DAILY_PROJECTION_MISMATCH'); end if;
  if abs(projection_30d-0.144)>0.0000000001 then failures:=array_append(failures,'THIRTY_DAY_PROJECTION_MISMATCH'); end if;

  -- Reserve thresholds for 1000 fully active Entry GPUs.
  if abs(expected_free_daily*1000-4.8)>0.0000000001 then failures:=array_append(failures,'NETWORK_DAILY_LIABILITY_MISMATCH'); end if;
  if abs(expected_free_30d*1000-144)>0.0000000001 then failures:=array_append(failures,'NETWORK_30D_LIABILITY_MISMATCH'); end if;
  if abs(min_reserve*1000-33.6)>0.0000000001 then failures:=array_append(failures,'NETWORK_7D_RESERVE_MISMATCH'); end if;

  if not exists (select 1 from cron.job where jobname='nextgen-starter-mining-enforcement') then failures:=array_append(failures,'CRON_ENFORCEMENT_JOB_MISSING'); end if;
  if pg_get_function_result('public.nextgen_live_mining_snapshot(text)'::regprocedure)<>'jsonb' then failures:=array_append(failures,'LIVE_SNAPSHOT_SIGNATURE_INVALID'); end if;

  -- Projection sanity under reserve: full reserve => 1x; half reserve => 0.5x; seven-day floor blocks renewal.
  if s.reserve_balance_usd>=expected_free_30d*1000 then
    if abs(least(s.reserve_balance_usd/(expected_free_30d*1000),1)-1)>0.0000001 then failures:=array_append(failures,'FULL_RESERVE_MULTIPLIER_INVALID'); end if;
  end if;

  return jsonb_build_object('success',cardinality(failures)=0,'failures',to_jsonb(failures),'free_slots',1000,'fallback_slot',1001,
    'entry_gpu_hashrate',s.entry_gpu_hashrate,'basic_cpu_hashrate',s.fallback_basic_cpu_hashrate,
    'entry_gpu_daily_usd',expected_free_daily,'entry_gpu_hourly_usd',projection_hourly,'entry_gpu_30d_usd',projection_30d,
    'all_1000_entry_gpu_daily_liability_usd',expected_free_daily*1000,
    'all_1000_entry_gpu_30d_liability_usd',expected_free_30d*1000,
    'all_1000_entry_gpu_minimum_7d_reserve_usd',min_reserve*1000,
    'as_of',now());
end;
$$;
revoke all on function public.nextgen_owner_starter_mining_e2e_1001() from public,anon,authenticated;

-- Automatic enforcement every minute. The Supabase project already has pg_cron 1.6.4 installed.
select cron.schedule('nextgen-starter-mining-enforcement', '* * * * *', $$select public.nextgen_process_starter_mining_expired();$$)
where not exists (select 1 from cron.job where jobname='nextgen-starter-mining-enforcement');

comment on table public.nextgen_starter_mining_settings is 'Owner-controlled promotional starter mining reserve and capacity policy.';
comment on table public.nextgen_starter_reserve_ledger is 'Auditable starter mining reserve funding and settlement ledger.';
comment on table public.nextgen_starter_mining_settlements is 'Authoritative server-side starter mining settlement ledger.';
