-- NextGen Miner: additional owner-controlled manual deposit destinations.
-- User-supplied addresses. QR assets are bundled under assets/deposit/qr/.
-- Coin-specific min deposit / confirmations / network fee remain NULL until explicitly configured by owner.

insert into public.ng_deposit_destinations (asset,network,provider,destination,label,min_deposit,confirmations_required,network_fee,warning_title,warning_message,first_deposit_note,qr_code_path,active,is_active) values
('USDT','TRC20 (Tron)','Manual','TJ9rfCGsTLrcg3sDVDN6V7bqpxfAqP8Hzu','Tether USD (USDT) · TRC20',NULL,NULL,NULL,'USDT TRC20 only','Send only USDT on the TRON TRC20 network. Sending the wrong coin or using a different network will result in a permanent loss of funds. We are not responsible for lost funds.','First-time deposits can take up to 30 minutes depending on network congestion. We do not support deposits from smart contracts — recovery fees apply.','assets/deposit/qr/usdt-trc20.png',TRUE,TRUE),
('USDT','ERC20 (Ethereum)','Manual','0x744943FC1b231dEc0140FE8A7acF67f9a34c1462','Tether USD (USDT) · ERC20',NULL,NULL,NULL,'USDT ERC20 only','Send only USDT on the Ethereum ERC20 network. Sending the wrong coin or using a different network will result in a permanent loss of funds. We are not responsible for lost funds.','First-time deposits can take up to 30 minutes depending on network congestion. We do not support deposits from smart contracts — recovery fees apply.','assets/deposit/qr/usdt-erc20.png',TRUE,TRUE),
('USDT','BEP20 (BSC)','Manual','0x9d2679074C80c2F94E6FB1DFaAA08A538458b82A','Tether USD (USDT) · BEP20',NULL,NULL,NULL,'USDT BEP20 only','Send only USDT on the BNB Smart Chain BEP20 network. Sending the wrong coin or using a different network will result in a permanent loss of funds. We are not responsible for lost funds.','First-time deposits can take up to 30 minutes depending on network congestion. We do not support deposits from smart contracts — recovery fees apply.','assets/deposit/qr/usdt-bep20.png',TRUE,TRUE),
('USDC','Solana (SPL)','Manual','AGLDdhiWxpERq793RTS3wgFgPxzwmymzM5WBXtBpDzEw','USD Coin (USDC)',NULL,NULL,NULL,'USDC only','Send only USDC on the Solana network. Sending the wrong coin or using a different network will result in a permanent loss of funds. We are not responsible for lost funds.','First-time deposits can take up to 30 minutes depending on network congestion. We do not support deposits from smart contracts — recovery fees apply.','assets/deposit/qr/usdc-solana.png',TRUE,TRUE),
('TRX','TRC20 (Tron)','Manual','TJ9rfCGsTLrcg3sDVDN6V7bqpxfAqP8Hzu','Tron (TRX)',NULL,NULL,NULL,'TRX only','Send only TRX on the TRON network. Sending the wrong coin or using a different network will result in a permanent loss of funds. We are not responsible for lost funds.','First-time deposits can take up to 30 minutes depending on network congestion. We do not support deposits from smart contracts — recovery fees apply.','assets/deposit/qr/trx.png',TRUE,TRUE),
('TON','TON','Manual','UQCRx3P4lugM7JItNckTtllYFrd5E8N9KL__jFtEbwXrLfgI','Toncoin (TON)',NULL,NULL,NULL,'TON only','Send only TON on the TON network. Sending the wrong coin or using a different network will result in a permanent loss of funds. We are not responsible for lost funds.','First-time deposits can take up to 30 minutes depending on network congestion. We do not support deposits from smart contracts — recovery fees apply.','assets/deposit/qr/ton.png',TRUE,TRUE),
('XLM','Stellar','Manual','GDMN42T63UMBCNNNKSKN2EIZGVLP75XSXWX2FRAROL3EDQPP37QEWAIP','Stellar (XLM)',NULL,NULL,NULL,'XLM only','Send only XLM on the Stellar network. Sending the wrong coin or using a different network will result in a permanent loss of funds. We are not responsible for lost funds.','First-time deposits can take up to 30 minutes depending on network congestion. We do not support deposits from smart contracts — recovery fees apply.','assets/deposit/qr/xlm.png',TRUE,TRUE),
('SOL','Solana','Manual','Gdfr731z6mZBQDzMyG9XE9aJDyM7M67dJDDpDSLLUAHy','Solana (SOL)',NULL,NULL,NULL,'SOL only','Send only SOL on the Solana network. Sending the wrong coin or using a different network will result in a permanent loss of funds. We are not responsible for lost funds.','First-time deposits can take up to 30 minutes depending on network congestion. We do not support deposits from smart contracts — recovery fees apply.','assets/deposit/qr/sol.png',TRUE,TRUE),
('XRP','XRP Ledger','Manual','rhVuiY5jeUnaDKbWYPh18j2kpGhnrYQ8nJ','Ripple (XRP)',NULL,NULL,NULL,'XRP only','Send only XRP on the XRP Ledger. Sending the wrong coin or using a different network will result in a permanent loss of funds. We are not responsible for lost funds.','First-time deposits can take up to 30 minutes depending on network congestion. We do not support deposits from smart contracts — recovery fees apply.','assets/deposit/qr/xrp.png',TRUE,TRUE),
('POL','Polygon PoS','Manual','0x3d7C9d1F9e6649cecffaC8668Bf3E62501441AA2','Polygon (POL)',NULL,NULL,NULL,'POL only','Send only POL on the Polygon network. Sending the wrong coin or using a different network will result in a permanent loss of funds. We are not responsible for lost funds.','First-time deposits can take up to 30 minutes depending on network congestion. We do not support deposits from smart contracts — recovery fees apply.','assets/deposit/qr/pol.png',TRUE,TRUE),
('PEPE','ERC20 (Ethereum)','Manual','0x744943FC1b231dEc0140FE8A7acF67f9a34c1462','Pepe (PEPE)',NULL,NULL,NULL,'PEPE only','Send only PEPE on the Ethereum ERC20 network. Sending the wrong coin or using a different network will result in a permanent loss of funds. We are not responsible for lost funds.','First-time deposits can take up to 30 minutes depending on network congestion. We do not support deposits from smart contracts — recovery fees apply.','assets/deposit/qr/pepe.png',TRUE,TRUE),
('XMR','Monero','Manual','4Bw5E7qSTCyUijTko5mQzSah8AQiJHnyV7XKBqwRkr6aWgRLNkUXvXkYrtVoj65GcmK7xQVCceJ6VgiCz4msqgdZ2Aui6ejTFsf2W6vJaY','Monero (XMR)',NULL,NULL,NULL,'XMR only','Send only XMR on the Monero network. Sending the wrong coin or using a different network will result in a permanent loss of funds. We are not responsible for lost funds.','First-time deposits can take up to 30 minutes depending on network congestion. We do not support deposits from smart contracts — recovery fees apply.','assets/deposit/qr/xmr.png',TRUE,TRUE),
('LTC','Litecoin','Manual','ltc1qta37f8tty47h3a0pc6659mu4ftfsvpq43h0vl5','Litecoin',NULL,NULL,NULL,'LTC only','Send only LTC on the Litecoin network. Sending the wrong coin or using a different network will result in a permanent loss of funds. We are not responsible for lost funds.','First-time deposits can take up to 30 minutes depending on network congestion. We do not support deposits from smart contracts — recovery fees apply.','assets/deposit/qr/ltc.png',TRUE,TRUE),
('BTC','Bitcoin','Manual','193WuwhXAmep4r1yFjceA8KHKvU2f9K4Cw','Bitcoin',NULL,NULL,NULL,'BTC only','Send only BTC on the Bitcoin network. Sending the wrong coin or using a different network will result in a permanent loss of funds. We are not responsible for lost funds.','First-time deposits can take up to 30 minutes depending on network congestion. We do not support deposits from smart contracts — recovery fees apply.','assets/deposit/qr/btc.png',TRUE,TRUE),
('BCH','Bitcoin Cash','Manual','bitcoincash:qqhnvvenm2gr0k4agrwtednnws8rqzfhm502yfaxwr','Bitcoin Cash',NULL,NULL,NULL,'BCH only','Send only BCH on the Bitcoin Cash network. Sending the wrong coin or using a different network will result in a permanent loss of funds. We are not responsible for lost funds.','First-time deposits can take up to 30 minutes depending on network congestion. We do not support deposits from smart contracts — recovery fees apply.','assets/deposit/qr/bch.png',TRUE,TRUE),
('ETH','Ethereum','Manual','0x744943FC1b231dEc0140FE8A7acF67f9a34c1462','Ethereum',NULL,NULL,NULL,'ETH only','Send only ETH on the Ethereum network. Sending the wrong coin or using a different network will result in a permanent loss of funds. We are not responsible for lost funds.','First-time deposits can take up to 30 minutes depending on network congestion. We do not support deposits from smart contracts — recovery fees apply.','assets/deposit/qr/eth.png',TRUE,TRUE),
('DOGE','Dogecoin','Manual','DBqUCjFFWfcpaMvVnScTMtpmLGJkge2vkD','Dogecoin',NULL,NULL,NULL,'DOGE only','Send only DOGE on the Dogecoin network. Sending the wrong coin or using a different network will result in a permanent loss of funds. We are not responsible for lost funds.','First-time deposits can take up to 30 minutes depending on network congestion. We do not support deposits from smart contracts — recovery fees apply.','assets/deposit/qr/doge.png',TRUE,TRUE),
('DASH','Dash','Manual','Xw9fPpBhAa2Ad5BQQP3Lo3on8EB3vZfZVA','Dash',NULL,NULL,NULL,'DASH only','Send only DASH on the Dash network. Sending the wrong coin or using a different network will result in a permanent loss of funds. We are not responsible for lost funds.','First-time deposits can take up to 30 minutes depending on network congestion. We do not support deposits from smart contracts — recovery fees apply.','assets/deposit/qr/dash.png',TRUE,TRUE),
('ADA','Cardano','Manual','addr1q8cvn5xlq9x6mkr2pfypxtn30ztzkjdtlpeuf37l5fpg5jgrv04gm3sqsl6pd6xl6dugjst626man23n3ur0vrwzqtrsr4ke5t','Cardano',NULL,NULL,NULL,'ADA only','Send only ADA on the Cardano network. Sending the wrong coin or using a different network will result in a permanent loss of funds. We are not responsible for lost funds.','First-time deposits can take up to 30 minutes depending on network congestion. We do not support deposits from smart contracts — recovery fees apply.','assets/deposit/qr/ada.png',TRUE,TRUE),
('DGB','DigiByte','Manual','DSU7dSm3vJ1XPbnTtvJAGsc1cB3jDQQ1bm','DigiByte',NULL,NULL,NULL,'DGB only','Send only DGB on the DigiByte network. Sending the wrong coin or using a different network will result in a permanent loss of funds. We are not responsible for lost funds.','First-time deposits can take up to 30 minutes depending on network congestion. We do not support deposits from smart contracts — recovery fees apply.','assets/deposit/qr/dgb.png',TRUE,TRUE)
on conflict (asset,network) do update set provider=excluded.provider,destination=excluded.destination,label=excluded.label,min_deposit=excluded.min_deposit,confirmations_required=excluded.confirmations_required,network_fee=excluded.network_fee,warning_title=excluded.warning_title,warning_message=excluded.warning_message,first_deposit_note=excluded.first_deposit_note,qr_code_path=excluded.qr_code_path,active=excluded.active,is_active=excluded.is_active;
