begin;

-- NEXTGEN MINER ECONOMIC IMPLEMENTATION
-- CP-01 Economic Configuration + CP-02 ledger foundations / safety hardening
-- Landing page remains untouched.

create table if not exists public.nextgen_economic_rule_versions (
  version text primary key,
  status text not null check (status in ('draft','active','retired')),
  denomination_diamond_per_usd numeric(30,8) not null check (denomination_diamond_per_usd > 0),
  mining_bps integer not null check (mining_bps between 0 and 10000),
  reserve_bps integer not null check (reserve_bps between 0 and 10000),
  donation_bps integer not null check (donation_bps between 0 and 10000),
  owner_platform_bps integer not null check (owner_platform_bps between 0 and 10000),
  settlement_hours integer not null check (settlement_hours between 1 and 168),
  merge_multiplier numeric(10,4) not null check (merge_multiplier > 1 and merge_multiplier <= 2),
  conversion_fee_bps integer not null check (conversion_fee_bps between 0 and 5000),
  created_at timestamptz not null default now(),
  activated_at timestamptz
);

insert into public.nextgen_economic_rule_versions
(version,status,denomination_diamond_per_usd,mining_bps,reserve_bps,donation_bps,owner_platform_bps,settlement_hours,merge_multiplier,conversion_fee_bps)
values
('economic_v1_0','active',10000,5000,3000,1000,1000,24,1.80,100)
on conflict (version) do update set
  status=excluded.status,
  denomination_diamond_per_usd=excluded.denomination_diamond_per_usd,
  mining_bps=excluded.mining_bps,
  reserve_bps=excluded.reserve_bps,
  donation_bps=excluded.donation_bps,
  owner_platform_bps=excluded.owner_platform_bps,
  settlement_hours=excluded.settlement_hours,
  merge_multiplier=excluded.merge_multiplier,
  conversion_fee_bps=excluded.conversion_fee_bps;

create table if not exists public.nextgen_reserve_ledger (
  id bigint generated by default as identity primary key,
  event_date date not null,
  source_type text not null,
  source_reference text,
  recognized_revenue_usd numeric(30,8) not null default 0 check (recognized_revenue_usd >= 0),
  reserve_in_usd numeric(30,8) not null default 0 check (reserve_in_usd >= 0),
  reserve_out_usd numeric(30,8) not null default 0 check (reserve_out_usd >= 0),
  balance_usd numeric(30,8) not null default 0 check (balance_usd >= 0),
  rule_version text not null references public.nextgen_economic_rule_versions(version),
  created_at timestamptz not null default now(),
  unique(event_date, source_type, source_reference)
);

alter table public.nextgen_mining_daily_pools
  add column if not exists reserve_allocation_usd numeric(30,8) not null default 0,
  add column if not exists reserve_balance_usd numeric(30,8) not null default 0,
  add column if not exists outstanding_mining_liability_usd numeric(30,8) not null default 0,
  add column if not exists reserve_coverage_ratio numeric(30,8) not null default 0,
  add column if not exists reserve_status text not null default 'healthy',
  add column if not exists reserve_safety_multiplier numeric(10,6) not null default 0.70,
  add column if not exists economic_rule_version text;

alter table public.nextgen_miner_levels
  add column if not exists efficiency numeric(10,6) not null default 1.0 check (efficiency between 0 and 2);

alter table public.nextgen_user_miners
  add column if not exists energy_percent numeric(6,3) not null default 100 check (energy_percent between 0 and 100),
  add column if not exists energy_updated_at timestamptz not null default now();

-- Frozen five-family Level 1-10 hashrate catalogue.
-- Values are written explicitly from the frozen checkpoint, not calculated at runtime.
with wanted(slug, lv, hs) as (
  values
  ('basic-cpu',1,20),('basic-cpu',2,36),('basic-cpu',3,65),('basic-cpu',4,117),('basic-cpu',5,211),('basic-cpu',6,380),('basic-cpu',7,684),('basic-cpu',8,1231),('basic-cpu',9,2216),('basic-cpu',10,3989),
  ('entry-gpu',1,60),('entry-gpu',2,108),('entry-gpu',3,195),('entry-gpu',4,351),('entry-gpu',5,632),('entry-gpu',6,1138),('entry-gpu',7,2048),('entry-gpu',8,3686),('entry-gpu',9,6635),('entry-gpu',10,11943),
  ('mini-rig',1,150),('mini-rig',2,270),('mini-rig',3,486),('mini-rig',4,875),('mini-rig',5,1575),('mini-rig',6,2835),('mini-rig',7,5103),('mini-rig',8,9185),('mini-rig',9,16533),('mini-rig',10,29759),
  ('gaming-pc',1,450),('gaming-pc',2,810),('gaming-pc',3,1458),('gaming-pc',4,2624),('gaming-pc',5,4723),('gaming-pc',6,8501),('gaming-pc',7,15302),('gaming-pc',8,27544),('gaming-pc',9,49579),('gaming-pc',10,89242),
  ('performance-rig',1,850),('performance-rig',2,1530),('performance-rig',3,2754),('performance-rig',4,4957),('performance-rig',5,8922),('performance-rig',6,16060),('performance-rig',7,28908),('performance-rig',8,52034),('performance-rig',9,93661),('performance-rig',10,168590)
)
update public.nextgen_miner_levels ml
set hashrate=w.hs
from public.nextgen_miner_catalog mc, wanted w
where ml.miner_id=mc.id and mc.slug=w.slug and ml.level=w.lv;

-- Frozen efficiency curve.
update public.nextgen_miner_levels
set efficiency = case level
  when 1 then 1.00 when 2 then 1.02 when 3 then 1.04 when 4 then 1.06 when 5 then 1.08
  when 6 then 1.10 when 7 then 1.12 when 8 then 1.14 when 9 then 1.16 when 10 then 1.18
end
where level between 1 and 10;

-- Align primary economic settings to frozen blueprint.
update public.nextgen_mining_economy_settings
set monetization_to_mining_bps=5000,
    owner_margin_bps=1000,
    updated_at=now()
where id=true;

update public.nextgen_economy_settings
set diamond_per_usd=10000,
    transaction_fee_bps=10,
    updated_at=now()
where id=true;

-- Revoke anonymous execution of privileged economic procedures.
revoke execute on function public.nextgen_get_landing_telemetry() from anon;
revoke execute on function public.nextgen_accrue_mining(text) from anon;
revoke execute on function public.nextgen_claim_daily_checkin() from anon;
revoke execute on function public.nextgen_claim_faucet() from anon;
revoke execute on function public.nextgen_claim_registration_bonus(uuid) from anon;
revoke execute on function public.nextgen_exchange_crypto_to_diamond(text,numeric) from anon;
revoke execute on function public.nextgen_purchase_miner(bigint) from anon;
revoke execute on function public.nextgen_upgrade_miner(bigint) from anon;
revoke execute on function public.nextgen_request_crypto_withdrawal(text,text,numeric,text) from anon;
revoke execute on function public.nextgen_request_withdrawal_v2(text,text,numeric,text) from anon;
revoke execute on function public.nextgen_prepare_mining_day(text) from anon;
revoke execute on function public.nextgen_mining_pool_snapshot(text) from anon;
revoke execute on function public.nextgen_wallet_snapshot() from anon;

-- Exact immutable-ish event protection on new reserve ledger.
alter table public.nextgen_reserve_ledger enable row level security;

drop policy if exists nextgen_reserve_ledger_admin_select on public.nextgen_reserve_ledger;
create policy nextgen_reserve_ledger_admin_select
on public.nextgen_reserve_ledger
for select to authenticated
using (public.nextgen_is_owner());

-- Public catalog/level reads remain allowed; economic mutation stays server-side.
commit;
